-- regitemtype.sql


/* =============================================
 * CREATE TABLE public."regitemtype"
 * ============================================*/
create table public."regitemtype" (
	regitemtype_id smallint generated by default as identity,
	constraint regitemtype_pk primary key (regitemtype_id)
);
comment on table public."regitemtype" is '';	


-- =============================================
-- FIELD: regitemtype_isdisabled boolean
-- =============================================
-- ADD regitemtype_isdisabled
alter table public."regitemtype" add regitemtype_isdisabled boolean not null default false;
comment on column public."regitemtype".regitemtype_isdisabled is '';

-- MODIFY regitemtype_isdisabled
alter table public."regitemtype"
	alter column regitemtype_isdisabled type boolean,
	ALTER COLUMN regitemtype_isdisabled SET DEFAULT false,
	ALTER COLUMN regitemtype_isdisabled SET NOT NULL;
comment on column public."regitemtype".regitemtype_isdisabled is '';


-- =============================================
-- FIELD: regitemtype_name text
-- =============================================
-- ADD regitemtype_name
alter table public."regitemtype" add regitemtype_name text  ;
comment on column public."regitemtype".regitemtype_name is '';

-- MODIFY regitemtype_name
alter table public."regitemtype"
	alter column regitemtype_name type text,
	ALTER COLUMN regitemtype_name DROP DEFAULT,
	ALTER COLUMN regitemtype_name DROP NOT NULL;
comment on column public."regitemtype".regitemtype_name is '';


-- =============================================
-- FIELD: regitemtype_descr text
-- =============================================
-- ADD regitemtype_descr
alter table public."regitemtype" add regitemtype_descr text  ;
comment on column public."regitemtype".regitemtype_descr is '';

-- MODIFY regitemtype_descr
alter table public."regitemtype"
	alter column regitemtype_descr type text,
	ALTER COLUMN regitemtype_descr DROP DEFAULT,
	ALTER COLUMN regitemtype_descr DROP NOT NULL;
comment on column public."regitemtype".regitemtype_descr is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."regitemtype" add _createby integer not null ;
comment on column public."regitemtype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."regitemtype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."regitemtype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."regitemtype" add _createdate timestamp with time zone not null default now();
comment on column public."regitemtype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."regitemtype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."regitemtype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."regitemtype" add _modifyby integer  ;
comment on column public."regitemtype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."regitemtype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."regitemtype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."regitemtype" add _modifydate timestamp with time zone  ;
comment on column public."regitemtype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."regitemtype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."regitemtype"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."regitemtype" add _timestamp timestamp with time zone not null default now();
comment on column public."regitemtype"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."regitemtype"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."regitemtype"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$regitemtype$_timestamp;
CREATE INDEX idx$public$regitemtype$_timestamp ON public.regitemtype (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."regitemtype"
	drop constraint uq$public$regitemtype$regitemtype_name;
	

-- Add unique index 
alter table  public."regitemtype"
	add constraint uq$public$regitemtype$regitemtype_name unique (regitemtype_name); 

