-- comp.sql


/* =============================================
 * CREATE TABLE public."comp"
 * ============================================*/
create table public."comp" (
	comp_id smallint generated by default as identity,
	constraint comp_pk primary key (comp_id)
);
comment on table public."comp" is '';	


-- =============================================
-- FIELD: comp_code text
-- =============================================
-- ADD comp_code
alter table public."comp" add comp_code text  ;
comment on column public."comp".comp_code is '';

-- MODIFY comp_code
alter table public."comp"
	alter column comp_code type text,
	ALTER COLUMN comp_code DROP DEFAULT,
	ALTER COLUMN comp_code DROP NOT NULL;
comment on column public."comp".comp_code is '';


-- =============================================
-- FIELD: comp_isdisabled boolean
-- =============================================
-- ADD comp_isdisabled
alter table public."comp" add comp_isdisabled boolean not null default false;
comment on column public."comp".comp_isdisabled is '';

-- MODIFY comp_isdisabled
alter table public."comp"
	alter column comp_isdisabled type boolean,
	ALTER COLUMN comp_isdisabled SET DEFAULT false,
	ALTER COLUMN comp_isdisabled SET NOT NULL;
comment on column public."comp".comp_isdisabled is '';


-- =============================================
-- FIELD: comp_isallowselect boolean
-- =============================================
-- ADD comp_isallowselect
alter table public."comp" add comp_isallowselect boolean not null default true;
comment on column public."comp".comp_isallowselect is '';

-- MODIFY comp_isallowselect
alter table public."comp"
	alter column comp_isallowselect type boolean,
	ALTER COLUMN comp_isallowselect SET DEFAULT true,
	ALTER COLUMN comp_isallowselect SET NOT NULL;
comment on column public."comp".comp_isallowselect is '';


-- =============================================
-- FIELD: comp_name text
-- =============================================
-- ADD comp_name
alter table public."comp" add comp_name text  ;
comment on column public."comp".comp_name is '';

-- MODIFY comp_name
alter table public."comp"
	alter column comp_name type text,
	ALTER COLUMN comp_name DROP DEFAULT,
	ALTER COLUMN comp_name DROP NOT NULL;
comment on column public."comp".comp_name is '';


-- =============================================
-- FIELD: comp_istax boolean
-- =============================================
-- ADD comp_istax
alter table public."comp" add comp_istax boolean not null default false;
comment on column public."comp".comp_istax is '';

-- MODIFY comp_istax
alter table public."comp"
	alter column comp_istax type boolean,
	ALTER COLUMN comp_istax SET DEFAULT false,
	ALTER COLUMN comp_istax SET NOT NULL;
comment on column public."comp".comp_istax is '';


-- =============================================
-- FIELD: comp_descr text
-- =============================================
-- ADD comp_descr
alter table public."comp" add comp_descr text  ;
comment on column public."comp".comp_descr is '';

-- MODIFY comp_descr
alter table public."comp"
	alter column comp_descr type text,
	ALTER COLUMN comp_descr DROP DEFAULT,
	ALTER COLUMN comp_descr DROP NOT NULL;
comment on column public."comp".comp_descr is '';


-- =============================================
-- FIELD: compgroup_id smallint
-- =============================================
-- ADD compgroup_id
alter table public."comp" add compgroup_id smallint  ;
comment on column public."comp".compgroup_id is '';

-- MODIFY compgroup_id
alter table public."comp"
	alter column compgroup_id type smallint,
	ALTER COLUMN compgroup_id DROP DEFAULT,
	ALTER COLUMN compgroup_id DROP NOT NULL;
comment on column public."comp".compgroup_id is '';


-- =============================================
-- FIELD: coa_id int
-- =============================================
-- ADD coa_id
alter table public."comp" add coa_id int  ;
comment on column public."comp".coa_id is '';

-- MODIFY coa_id
alter table public."comp"
	alter column coa_id type int,
	ALTER COLUMN coa_id DROP DEFAULT,
	ALTER COLUMN coa_id DROP NOT NULL;
comment on column public."comp".coa_id is '';


-- =============================================
-- FIELD: adv_coa_id int
-- =============================================
-- ADD adv_coa_id
alter table public."comp" add adv_coa_id int  ;
comment on column public."comp".adv_coa_id is '';

-- MODIFY adv_coa_id
alter table public."comp"
	alter column adv_coa_id type int,
	ALTER COLUMN adv_coa_id DROP DEFAULT,
	ALTER COLUMN adv_coa_id DROP NOT NULL;
comment on column public."comp".adv_coa_id is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."comp" add _createby integer not null ;
comment on column public."comp"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."comp"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."comp"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."comp" add _createdate timestamp with time zone not null default now();
comment on column public."comp"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."comp"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."comp"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."comp" add _modifyby integer  ;
comment on column public."comp"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."comp"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."comp"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."comp" add _modifydate timestamp with time zone  ;
comment on column public."comp"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."comp"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."comp"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."comp" add _timestamp timestamp with time zone not null default now();
comment on column public."comp"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."comp"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."comp"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$comp$_timestamp;
CREATE INDEX idx$public$comp$_timestamp ON public.comp (_timestamp);


-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."comp" DROP CONSTRAINT fk$public$comp$compgroup_id;
ALTER TABLE public."comp" DROP CONSTRAINT fk$public$comp$coa_id;
ALTER TABLE public."comp" DROP CONSTRAINT fk$public$comp$adv_coa_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."comp"
	ADD CONSTRAINT fk$public$comp$compgroup_id
	FOREIGN KEY (compgroup_id)
	REFERENCES public."compgroup"(compgroup_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$comp$compgroup_id;
CREATE INDEX idx_fk$public$comp$compgroup_id ON public."comp"(compgroup_id);	


ALTER TABLE public."comp"
	ADD CONSTRAINT fk$public$comp$coa_id
	FOREIGN KEY (coa_id)
	REFERENCES public."coa"(coa_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$comp$coa_id;
CREATE INDEX idx_fk$public$comp$coa_id ON public."comp"(coa_id);	


ALTER TABLE public."comp"
	ADD CONSTRAINT fk$public$comp$adv_coa_id
	FOREIGN KEY (adv_coa_id)
	REFERENCES public."coa"(coa_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$comp$adv_coa_id;
CREATE INDEX idx_fk$public$comp$adv_coa_id ON public."comp"(adv_coa_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."comp"
	drop constraint uq$public$comp$comp_name;
	

-- Add unique index 
alter table  public."comp"
	add constraint uq$public$comp$comp_name unique (comp_name); 

