-- skuopt.sql


/* =============================================
 * CREATE TABLE public."skuopt"
 * ============================================*/
create table public."skuopt" (
	skuopt_id smallint generated by default as identity,
	constraint skuopt_pk primary key (skuopt_id)
);
comment on table public."skuopt" is '';	


-- =============================================
-- FIELD: skuopt_name text
-- =============================================
-- ADD skuopt_name
alter table public."skuopt" add skuopt_name text  ;
comment on column public."skuopt".skuopt_name is '';

-- MODIFY skuopt_name
alter table public."skuopt"
	alter column skuopt_name type text,
	ALTER COLUMN skuopt_name DROP DEFAULT,
	ALTER COLUMN skuopt_name DROP NOT NULL;
comment on column public."skuopt".skuopt_name is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."skuopt" add _createby integer not null ;
comment on column public."skuopt"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."skuopt"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."skuopt"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."skuopt" add _createdate timestamp with time zone not null default now();
comment on column public."skuopt"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."skuopt"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."skuopt"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."skuopt" add _modifyby integer  ;
comment on column public."skuopt"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."skuopt"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."skuopt"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."skuopt" add _modifydate timestamp with time zone  ;
comment on column public."skuopt"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."skuopt"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."skuopt"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."skuopt" add _timestamp timestamp with time zone not null default now();
comment on column public."skuopt"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."skuopt"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."skuopt"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$skuopt$_timestamp;
CREATE INDEX idx$public$skuopt$_timestamp ON public.skuopt (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."skuopt"
	drop constraint uq$public$skuopt$skuopt_name;
	

-- Add unique index 
alter table  public."skuopt"
	add constraint uq$public$skuopt$skuopt_name unique (skuopt_name); 

