-- uomtype.sql


/* =============================================
 * CREATE TABLE public."uomtype"
 * ============================================*/
create table public."uomtype" (
	uomtype_id smallint generated by default as identity,
	constraint uomtype_pk primary key (uomtype_id)
);
comment on table public."uomtype" is '';	


-- =============================================
-- FIELD: uomtype_name text
-- =============================================
-- ADD uomtype_name
alter table public."uomtype" add uomtype_name text  ;
comment on column public."uomtype".uomtype_name is '';

-- MODIFY uomtype_name
alter table public."uomtype"
	alter column uomtype_name type text,
	ALTER COLUMN uomtype_name DROP DEFAULT,
	ALTER COLUMN uomtype_name DROP NOT NULL;
comment on column public."uomtype".uomtype_name is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."uomtype" add _createby integer not null ;
comment on column public."uomtype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."uomtype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."uomtype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."uomtype" add _createdate timestamp with time zone not null default now();
comment on column public."uomtype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."uomtype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."uomtype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."uomtype" add _modifyby integer  ;
comment on column public."uomtype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."uomtype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."uomtype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."uomtype" add _modifydate timestamp with time zone  ;
comment on column public."uomtype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."uomtype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."uomtype"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."uomtype" add _timestamp timestamp with time zone not null default now();
comment on column public."uomtype"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."uomtype"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."uomtype"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$uomtype$_timestamp;
CREATE INDEX idx$public$uomtype$_timestamp ON public.uomtype (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."uomtype"
	drop constraint uq$public$uomtype$uomtype_name;
	

-- Add unique index 
alter table  public."uomtype"
	add constraint uq$public$uomtype$uomtype_name unique (uomtype_name); 

