-- regtype.sql


/* =============================================
 * CREATE TABLE public."regtype"
 * ============================================*/
create table public."regtype" (
	regtype_id int generated by default as identity,
	constraint regtype_pk primary key (regtype_id)
);
comment on table public."regtype" is '';	


-- =============================================
-- FIELD: regtype_isdisabled boolean
-- =============================================
-- ADD regtype_isdisabled
alter table public."regtype" add regtype_isdisabled boolean not null default false;
comment on column public."regtype".regtype_isdisabled is '';

-- MODIFY regtype_isdisabled
alter table public."regtype"
	alter column regtype_isdisabled type boolean,
	ALTER COLUMN regtype_isdisabled SET DEFAULT false,
	ALTER COLUMN regtype_isdisabled SET NOT NULL;
comment on column public."regtype".regtype_isdisabled is '';


-- =============================================
-- FIELD: regtype_name text
-- =============================================
-- ADD regtype_name
alter table public."regtype" add regtype_name text  ;
comment on column public."regtype".regtype_name is '';

-- MODIFY regtype_name
alter table public."regtype"
	alter column regtype_name type text,
	ALTER COLUMN regtype_name DROP DEFAULT,
	ALTER COLUMN regtype_name DROP NOT NULL;
comment on column public."regtype".regtype_name is '';


-- =============================================
-- FIELD: regtype_descr text
-- =============================================
-- ADD regtype_descr
alter table public."regtype" add regtype_descr text  ;
comment on column public."regtype".regtype_descr is '';

-- MODIFY regtype_descr
alter table public."regtype"
	alter column regtype_descr type text,
	ALTER COLUMN regtype_descr DROP DEFAULT,
	ALTER COLUMN regtype_descr DROP NOT NULL;
comment on column public."regtype".regtype_descr is '';


-- =============================================
-- FIELD: regtype_isallowallbrand boolean
-- =============================================
-- ADD regtype_isallowallbrand
alter table public."regtype" add regtype_isallowallbrand boolean not null default false;
comment on column public."regtype".regtype_isallowallbrand is '';

-- MODIFY regtype_isallowallbrand
alter table public."regtype"
	alter column regtype_isallowallbrand type boolean,
	ALTER COLUMN regtype_isallowallbrand SET DEFAULT false,
	ALTER COLUMN regtype_isallowallbrand SET NOT NULL;
comment on column public."regtype".regtype_isallowallbrand is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."regtype" add _createby integer not null ;
comment on column public."regtype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."regtype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."regtype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."regtype" add _createdate timestamp with time zone not null default now();
comment on column public."regtype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."regtype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."regtype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."regtype" add _modifyby integer  ;
comment on column public."regtype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."regtype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."regtype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."regtype" add _modifydate timestamp with time zone  ;
comment on column public."regtype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."regtype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."regtype"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."regtype" add _timestamp timestamp with time zone not null default now();
comment on column public."regtype"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."regtype"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."regtype"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$regtype$_timestamp;
CREATE INDEX idx$public$regtype$_timestamp ON public.regtype (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Add unique index 
alter table  public."regtype"
	add constraint uq$public$regtype$regtype_name unique (regtype_name); 

