-- permission.sql


/* =============================================
 * CREATE TABLE core."permission"
 * ============================================*/
create table core."permission" (
	permission_id int generated by default as identity,
	constraint permission_pk primary key (permission_id)
);
comment on table core."permission" is '';	


-- =============================================
-- FIELD: permission_name text
-- =============================================
-- ADD permission_name
alter table core."permission" add permission_name text  ;
comment on column core."permission".permission_name is '';

-- MODIFY permission_name
alter table core."permission"
	alter column permission_name type text,
	ALTER COLUMN permission_name DROP DEFAULT,
	ALTER COLUMN permission_name DROP NOT NULL;
comment on column core."permission".permission_name is '';


-- =============================================
-- FIELD: permission_isdisabled boolean
-- =============================================
-- ADD permission_isdisabled
alter table core."permission" add permission_isdisabled boolean not null default false;
comment on column core."permission".permission_isdisabled is '';

-- MODIFY permission_isdisabled
alter table core."permission"
	alter column permission_isdisabled type boolean,
	ALTER COLUMN permission_isdisabled SET DEFAULT false,
	ALTER COLUMN permission_isdisabled SET NOT NULL;
comment on column core."permission".permission_isdisabled is '';


-- =============================================
-- FIELD: permission_descr text
-- =============================================
-- ADD permission_descr
alter table core."permission" add permission_descr text  ;
comment on column core."permission".permission_descr is '';

-- MODIFY permission_descr
alter table core."permission"
	alter column permission_descr type text,
	ALTER COLUMN permission_descr DROP DEFAULT,
	ALTER COLUMN permission_descr DROP NOT NULL;
comment on column core."permission".permission_descr is '';


-- =============================================
-- FIELD: permission_defaultvalue text
-- =============================================
-- ADD permission_defaultvalue
alter table core."permission" add permission_defaultvalue text  ;
comment on column core."permission".permission_defaultvalue is '';

-- MODIFY permission_defaultvalue
alter table core."permission"
	alter column permission_defaultvalue type text,
	ALTER COLUMN permission_defaultvalue DROP DEFAULT,
	ALTER COLUMN permission_defaultvalue DROP NOT NULL;
comment on column core."permission".permission_defaultvalue is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table core."permission" add _createby integer not null ;
comment on column core."permission"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table core."permission"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column core."permission"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table core."permission" add _createdate timestamp with time zone not null default now();
comment on column core."permission"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table core."permission"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column core."permission"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table core."permission" add _modifyby integer  ;
comment on column core."permission"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table core."permission"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column core."permission"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table core."permission" add _modifydate timestamp with time zone  ;
comment on column core."permission"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table core."permission"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column core."permission"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table core."permission" add _timestamp timestamp with time zone not null default now();
comment on column core."permission"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table core."permission"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column core."permission"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS core.idx$core$permission$_timestamp;
CREATE INDEX idx$core$permission$_timestamp ON core.permission (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table core."permission"
	drop constraint uq$core$permission$permission_name;
	

-- Add unique index 
alter table  core."permission"
	add constraint uq$core$permission$permission_name unique (permission_name); 

