-- compgroup.sql


/* =============================================
 * CREATE TABLE public."compgroup"
 * ============================================*/
create table public."compgroup" (
	compgroup_id smallint generated by default as identity,
	constraint compgroup_pk primary key (compgroup_id)
);
comment on table public."compgroup" is '';	


-- =============================================
-- FIELD: compgroup_name text
-- =============================================
-- ADD compgroup_name
alter table public."compgroup" add compgroup_name text  ;
comment on column public."compgroup".compgroup_name is '';

-- MODIFY compgroup_name
alter table public."compgroup"
	alter column compgroup_name type text,
	ALTER COLUMN compgroup_name DROP DEFAULT,
	ALTER COLUMN compgroup_name DROP NOT NULL;
comment on column public."compgroup".compgroup_name is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."compgroup" add _createby integer not null ;
comment on column public."compgroup"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."compgroup"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."compgroup"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."compgroup" add _createdate timestamp with time zone not null default now();
comment on column public."compgroup"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."compgroup"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."compgroup"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."compgroup" add _modifyby integer  ;
comment on column public."compgroup"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."compgroup"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."compgroup"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."compgroup" add _modifydate timestamp with time zone  ;
comment on column public."compgroup"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."compgroup"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."compgroup"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."compgroup" add _timestamp timestamp with time zone not null default now();
comment on column public."compgroup"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."compgroup"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."compgroup"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$compgroup$_timestamp;
CREATE INDEX idx$public$compgroup$_timestamp ON public.compgroup (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."compgroup"
	drop constraint uq$public$compgroup$compgroup_name;
	

-- Add unique index 
alter table  public."compgroup"
	add constraint uq$public$compgroup$compgroup_name unique (compgroup_name); 

