-- uom.sql


/* =============================================
 * CREATE TABLE public."uom"
 * ============================================*/
create table public."uom" (
	uom_id smallint generated by default as identity,
	constraint uom_pk primary key (uom_id)
);
comment on table public."uom" is '';	


-- =============================================
-- FIELD: uom_name text
-- =============================================
-- ADD uom_name
alter table public."uom" add uom_name text  ;
comment on column public."uom".uom_name is '';

-- MODIFY uom_name
alter table public."uom"
	alter column uom_name type text,
	ALTER COLUMN uom_name DROP DEFAULT,
	ALTER COLUMN uom_name DROP NOT NULL;
comment on column public."uom".uom_name is '';


-- =============================================
-- FIELD: isusedecimal boolean
-- =============================================
-- ADD isusedecimal
alter table public."uom" add isusedecimal boolean not null default false;
comment on column public."uom".isusedecimal is '';

-- MODIFY isusedecimal
alter table public."uom"
	alter column isusedecimal type boolean,
	ALTER COLUMN isusedecimal SET DEFAULT false,
	ALTER COLUMN isusedecimal SET NOT NULL;
comment on column public."uom".isusedecimal is '';


-- =============================================
-- FIELD: uomtype_id smallint
-- =============================================
-- ADD uomtype_id
alter table public."uom" add uomtype_id smallint  ;
comment on column public."uom".uomtype_id is '';

-- MODIFY uomtype_id
alter table public."uom"
	alter column uomtype_id type smallint,
	ALTER COLUMN uomtype_id DROP DEFAULT,
	ALTER COLUMN uomtype_id DROP NOT NULL;
comment on column public."uom".uomtype_id is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."uom" add _createby integer not null ;
comment on column public."uom"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."uom"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."uom"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."uom" add _createdate timestamp with time zone not null default now();
comment on column public."uom"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."uom"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."uom"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."uom" add _modifyby integer  ;
comment on column public."uom"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."uom"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."uom"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."uom" add _modifydate timestamp with time zone  ;
comment on column public."uom"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."uom"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."uom"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."uom" add _timestamp timestamp with time zone not null default now();
comment on column public."uom"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."uom"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."uom"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$uom$_timestamp;
CREATE INDEX idx$public$uom$_timestamp ON public.uom (_timestamp);


-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."uom" DROP CONSTRAINT fk$public$uom$uomtype_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."uom"
	ADD CONSTRAINT fk$public$uom$uomtype_id
	FOREIGN KEY (uomtype_id)
	REFERENCES public."uomtype"(uomtype_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$uom$uomtype_id;
CREATE INDEX idx_fk$public$uom$uomtype_id ON public."uom"(uomtype_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."uom"
	drop constraint uq$public$uom$uom_name;
	

-- Add unique index 
alter table  public."uom"
	add constraint uq$public$uom$uom_name unique (uom_name); 

