-- ctg.sql


/* =============================================
 * CREATE TABLE public."ctg"
 * ============================================*/
create table public."ctg" (
	ctg_id int generated by default as identity,
	constraint ctg_pk primary key (ctg_id)
);
comment on table public."ctg" is '';	


-- =============================================
-- FIELD: ctg_isdisabled boolean
-- =============================================
-- ADD ctg_isdisabled
alter table public."ctg" add ctg_isdisabled boolean not null default false;
comment on column public."ctg".ctg_isdisabled is '';

-- MODIFY ctg_isdisabled
alter table public."ctg"
	alter column ctg_isdisabled type boolean,
	ALTER COLUMN ctg_isdisabled SET DEFAULT false,
	ALTER COLUMN ctg_isdisabled SET NOT NULL;
comment on column public."ctg".ctg_isdisabled is '';


-- =============================================
-- FIELD: ctg_name text
-- =============================================
-- ADD ctg_name
alter table public."ctg" add ctg_name text  ;
comment on column public."ctg".ctg_name is '';

-- MODIFY ctg_name
alter table public."ctg"
	alter column ctg_name type text,
	ALTER COLUMN ctg_name DROP DEFAULT,
	ALTER COLUMN ctg_name DROP NOT NULL;
comment on column public."ctg".ctg_name is '';


-- =============================================
-- FIELD: ctg_descr text
-- =============================================
-- ADD ctg_descr
alter table public."ctg" add ctg_descr text  ;
comment on column public."ctg".ctg_descr is '';

-- MODIFY ctg_descr
alter table public."ctg"
	alter column ctg_descr type text,
	ALTER COLUMN ctg_descr DROP DEFAULT,
	ALTER COLUMN ctg_descr DROP NOT NULL;
comment on column public."ctg".ctg_descr is '';


-- =============================================
-- FIELD: gro_id smallint
-- =============================================
-- ADD gro_id
alter table public."ctg" add gro_id smallint  ;
comment on column public."ctg".gro_id is '';

-- MODIFY gro_id
alter table public."ctg"
	alter column gro_id type smallint,
	ALTER COLUMN gro_id DROP DEFAULT,
	ALTER COLUMN gro_id DROP NOT NULL;
comment on column public."ctg".gro_id is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."ctg" add _createby integer not null ;
comment on column public."ctg"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."ctg"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."ctg"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."ctg" add _createdate timestamp with time zone not null default now();
comment on column public."ctg"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."ctg"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."ctg"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."ctg" add _modifyby integer  ;
comment on column public."ctg"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."ctg"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."ctg"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."ctg" add _modifydate timestamp with time zone  ;
comment on column public."ctg"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."ctg"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."ctg"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."ctg" add _timestamp timestamp with time zone not null default now();
comment on column public."ctg"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."ctg"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."ctg"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$ctg$_timestamp;
CREATE INDEX idx$public$ctg$_timestamp ON public.ctg (_timestamp);


-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."ctg" DROP CONSTRAINT fk$public$ctg$gro_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."ctg"
	ADD CONSTRAINT fk$public$ctg$gro_id
	FOREIGN KEY (gro_id)
	REFERENCES public."gro"(gro_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$ctg$gro_id;
CREATE INDEX idx_fk$public$ctg$gro_id ON public."ctg"(gro_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Add unique index 
alter table  public."ctg"
	add constraint uq$public$ctg$ctg_name unique (ctg_name); 

