/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/itemclass.apiext.js'

const moduleName = 'itemclass'
const headerSectionName = 'header'
const headerTableName = 'public.itemclass' 
const structTableName = 'public.itemclassstruct'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await itemclass_init(this, body) }

	// extender call
	async execute(body) { return await itemclass_execute(this, body) }

	// header
	async headerList(body) { return await itemclass_headerList(this, body) }
	async headerOpen(body) { return await itemclass_headerOpen(this, body) }
	async headerUpdate(body) { return await itemclass_headerUpdate(this, body)}
	async headerCreate(body) { return await itemclass_headerCreate(this, body)}
	async headerDelete(body) { return await itemclass_headerDelete(this, body) }

	
	// struct	
	async structList(body) { return await itemclass_structList(this, body) }
	async structOpen(body) { return await itemclass_structOpen(this, body) }
	async structUpdate(body) { return await itemclass_structUpdate(this, body)}
	async structCreate(body) { return await itemclass_structCreate(this, body) }
	async structDelete(body) { return await itemclass_structDelete(this, body) }
	async structDeleteRows(body) { return await itemclass_structDeleteRows(this, body) }
			
}	

// init module
async function itemclass_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.itemclass_init === 'function') {
			// export async function itemclass_init(self, initialData) {}
			await Extender.itemclass_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function itemclass_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, itemclass_log) {}
		return await Extender[fnName](self, db, body, itemclass_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function itemclass_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function itemclass_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `itemclass_name ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: struct_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.itemclass.owner_struct_id)
			{
				const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', row.owner_struct_id)
				row.struct_name = struct_name
			}
			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function itemclass_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { itemclass_id: id }
		const searchMap = { itemclass_id: `itemclass_id = \${itemclass_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: struct_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.itemclass.owner_struct_id)
		{
			const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', data.owner_struct_id)
			data.struct_name = struct_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function itemclass_headerCreate(self, body) {
	const { source='itemclass', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data, ['itemclass_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			itemclass_log(self, body, startTime, tablename, ret.itemclass_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function itemclass_headerUpdate(self, body) {
	const { source='itemclass', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['itemclass_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			itemclass_log(self, body, startTime, tablename, data.itemclass_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function itemclass_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {itemclass_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data struct
			{
				const sql = `select * from ${structTableName} where itemclass_id=\${itemclass_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowstruct of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.structDeleting === 'function') {
						// export async function structDeleting(self, tx, rowstruct, logMetadata) {}
						await Extender.structDeleting(self, tx, rowstruct, logMetadata)
					}

					const param = {itemclassstruct_id: rowstruct.itemclassstruct_id}
					const cmd = sqlUtil.createDeleteCommand(structTableName, ['itemclassstruct_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.structDeleted === 'function') {
						// export async function structDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.structDeleted(self, tx, deletedRow, logMetadata)
					}					

					itemclass_log(self, body, startTime, structTableName, rowstruct.itemclassstruct_id, 'DELETE', {rowdata: deletedRow})
					itemclass_log(self, body, startTime, headerTableName, rowstruct.itemclass_id, 'DELETE ROW STRUCT', {itemclassstruct_id: rowstruct.itemclassstruct_id, tablename: structTableName}, `removed: ${rowstruct.itemclassstruct_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['itemclass_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			itemclass_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// struct	

async function itemclass_structList(self, body) {
	const tablename = structTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		itemclass_id: `itemclass_id=try_cast_bigint(\${itemclass_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.itemclassstruct_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.structListCriteria === 'function') {
			// export async function structListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.structListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: struct_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.itemclass.struct_id)
			{
				const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', row.struct_id)
				row.struct_name = struct_name
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function itemclass_structOpen(self, body) {
	const tablename = structTableName

	try {
		const { id } = body 
		const criteria = { itemclassstruct_id: id }
		const searchMap = { itemclassstruct_id: `itemclassstruct_id = \${itemclassstruct_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: struct_name dari field struct_name pada table public.struct dimana (public.struct.struct_id = public.itemclass.struct_id)
		{
			const { struct_name } = await sqlUtil.lookupdb(db, 'public.struct', 'struct_id', data.struct_id)
			data.struct_name = struct_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function structOpen(self, db, data) {}
		if (typeof Extender.structOpen === 'function') {
			// export async function structOpen(self, db, data) {}
			await Extender.structOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function itemclass_structCreate(self, body) {
	const { source='itemclass', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = structTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'struct', 
				prefix: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.itemclassstruct_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.structCreating === 'function') {
				// export async function structCreating(self, tx, data, seqdata, args) {}
				await Extender.structCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.structCreated === 'function') {
				// export async function structCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.structCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			itemclass_log(self, body, startTime, tablename, ret.itemclassstruct_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function itemclass_structUpdate(self, body) {
	const { source='itemclass', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = structTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.structUpdating === 'function') {
				// export async function structUpdating(self, tx, data) {}
				await Extender.structUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['itemclassstruct_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.structUpdated === 'function') {
				// export async function structUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.structUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			itemclass_log(self, body, startTime, tablename, data.itemclassstruct_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function itemclass_structDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = structTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {itemclassstruct_id: id}
			const sql = `select * from ${structTableName} where itemclassstruct_id=\${itemclassstruct_id}`
			const rowstruct = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.structDeleting === 'function') {
				// export async function structDeleting(self, tx, rowstruct, logMetadata) {}
				await Extender.structDeleting(self, tx, rowstruct, logMetadata)
			}

			const param = {itemclassstruct_id: rowstruct.itemclassstruct_id}
			const cmd = sqlUtil.createDeleteCommand(structTableName, ['itemclassstruct_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.structDeleted === 'function') {
				// export async function structDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.structDeleted(self, tx, deletedRow, logMetadata)
			}					

			itemclass_log(self, body, startTime, structTableName, rowstruct.itemclassstruct_id, 'DELETE', {rowdata: deletedRow})
			itemclass_log(self, body, startTime, headerTableName, rowstruct.itemclass_id, 'DELETE ROW STRUCT', {itemclassstruct_id: rowstruct.itemclassstruct_id, tablename: structTableName}, `removed: ${rowstruct.itemclassstruct_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function itemclass_structDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = structTableName


	try {

		let itemclass_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {itemclassstruct_id: id}
				const sql = `select * from ${structTableName} where itemclassstruct_id=\${itemclassstruct_id}`
				const rowstruct = await tx.oneOrNone(sql, dataToRemove)
				itemclass_id = rowstruct.itemclass_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.structDeleting === 'function') {
					// async function structDeleting(self, tx, rowstruct, logMetadata) {}
					await Extender.structDeleting(self, tx, rowstruct, logMetadata)
				}

				const param = {itemclassstruct_id: rowstruct.itemclassstruct_id}
				const cmd = sqlUtil.createDeleteCommand(structTableName, ['itemclassstruct_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.structDeleted === 'function') {
					// export async function structDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.structDeleted(self, tx, deletedRow, logMetadata)
				}					

				itemclass_log(self, body, startTime, structTableName, rowstruct.itemclassstruct_id, 'DELETE', {rowdata: deletedRow})
				itemclass_log(self, body, startTime, headerTableName, rowstruct.itemclass_id, 'DELETE ROW STRUCT', {itemclassstruct_id: rowstruct.itemclassstruct_id, tablename: structTableName}, `removed: ${rowstruct.itemclassstruct_id}`)
			}
		})
		

		const res = {
			deleted: true,
			itemclass_id: itemclass_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'structRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function structRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	