/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerDocument } from '@agung_dhewe/webapps/src/sequencerdoc.js' 

import * as Extender from './extenders/mov.apiext.js'

const moduleName = 'mov'
const headerSectionName = 'header'
const headerTableName = 'public.mov' 
const headerPrimaryKey = 'mov_id' 	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await mov_init(this, body) }

	// extender call
	async execute(body) { return await mov_execute(this, body) }

	// header
	async headerList(body) { return await mov_headerList(this, body) }
	async headerOpen(body) { return await mov_headerOpen(this, body) }
	async headerUpdate(body) { return await mov_headerUpdate(this, body)}
	async headerCreate(body) { return await mov_headerCreate(this, body)}
	async headerDelete(body) { return await mov_headerDelete(this, body) }

			
}	

// init module
async function mov_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.mov_init === 'function') {
			// export async function mov_init(self, initialData) {}
			await Extender.mov_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function mov_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, mov_log) {}
		return await Extender[fnName](self, db, body, mov_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function mov_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function mov_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `mov_doc = \${searchtext}`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: movtype_code dari field movtype_code pada table public.movtype dimana (public.movtype.movtype_id = public.mov.movtype_id)
			if (row.movtype_id !== undefined) {
				const { movtype_code } = await sqlUtil.lookupdb(db, 'public.movtype', 'movtype_id', row.movtype_id)
				row.movtype_code = movtype_code ?? null
			}
			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.mov.brand_id)
			if (row.brand_id !== undefined) {
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name ?? null
			}
			// lookup: po_descr dari field po_descr pada table public.po dimana (public.po.po_id = public.mov.po_id)
			if (row.po_id !== undefined) {
				const { po_descr } = await sqlUtil.lookupdb(db, 'public.po', 'po_id', row.po_id)
				row.po_descr = po_descr ?? null
			}
			// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.mov.partner_id)
			if (row.partner_id !== undefined) {
				const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', row.partner_id)
				row.partner_name = partner_name ?? null
			}
			// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.mov.sea_id)
			if (row.sea_id !== undefined) {
				const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', row.sea_id)
				row.sea_name = sea_name ?? null
			}
			// lookup: curr_name dari field curr_name pada table public.curr dimana (public.curr.curr_id = public.mov.curr_id)
			if (row.curr_id !== undefined) {
				const { curr_name } = await sqlUtil.lookupdb(db, 'public.curr', 'curr_id', row.curr_id)
				row.curr_name = curr_name ?? null
			}
			// lookup: ori_site_name dari field site_name pada table public.site dimana (public.site.site_id = public.mov.ori_site_id)
			if (row.ori_site_id !== undefined) {
				const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', row.ori_site_id)
				row.ori_site_name = site_name ?? null
			}
			// lookup: des_site_name dari field site_name pada table public.site dimana (public.site.site_id = public.mov.des_site_id)
			if (row.des_site_id !== undefined) {
				const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', row.des_site_id)
				row.des_site_name = site_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function mov_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { mov_id: id }
		const searchMap = { mov_id: `mov_id = \${mov_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: movtype_code dari field movtype_code pada table public.movtype dimana (public.movtype.movtype_id = public.mov.movtype_id)
		if (data.movtype_id !== undefined) {
			const { movtype_code } = await sqlUtil.lookupdb(db, 'public.movtype', 'movtype_id', data.movtype_id)
			data.movtype_code = movtype_code ?? null
		}
		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.mov.brand_id)
		if (data.brand_id !== undefined) {
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name ?? null
		}
		// lookup: po_descr dari field po_descr pada table public.po dimana (public.po.po_id = public.mov.po_id)
		if (data.po_id !== undefined) {
			const { po_descr } = await sqlUtil.lookupdb(db, 'public.po', 'po_id', data.po_id)
			data.po_descr = po_descr ?? null
		}
		// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.mov.partner_id)
		if (data.partner_id !== undefined) {
			const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', data.partner_id)
			data.partner_name = partner_name ?? null
		}
		// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.mov.sea_id)
		if (data.sea_id !== undefined) {
			const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', data.sea_id)
			data.sea_name = sea_name ?? null
		}
		// lookup: curr_name dari field curr_name pada table public.curr dimana (public.curr.curr_id = public.mov.curr_id)
		if (data.curr_id !== undefined) {
			const { curr_name } = await sqlUtil.lookupdb(db, 'public.curr', 'curr_id', data.curr_id)
			data.curr_name = curr_name ?? null
		}
		// lookup: ori_site_name dari field site_name pada table public.site dimana (public.site.site_id = public.mov.ori_site_id)
		if (data.ori_site_id !== undefined) {
			const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', data.ori_site_id)
			data.ori_site_name = site_name ?? null
		}
		// lookup: des_site_name dari field site_name pada table public.site dimana (public.site.site_id = public.mov.des_site_id)
		if (data.des_site_id !== undefined) {
			const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', data.des_site_id)
			data.des_site_name = site_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function mov_headerCreate(self, body) {
	const { source='mov', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'XX' }

			// buat sequencer document	
			const sequencer = createSequencerDocument(tx, { 
				COMPANY_CODE: req.app.locals.appConfig.COMPANY_CODE,
				blockLength: 3,
				numberLength: 6,
			})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate data sesuai prefix dari doc_id (default:  XX) reset pertahun
			const seqdata = await sequencer.yearly(args.doc_id)	
			data.mov_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}			
			
			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			mov_log(self, body, startTime, tablename, ret.mov_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function mov_headerUpdate(self, body) {
	const { source='mov', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['mov_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			mov_log(self, body, startTime, tablename, data.mov_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function mov_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {mov_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['mov_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			mov_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}


	