/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerDocument } from '@agung_dhewe/webapps/src/sequencerdoc.js' 
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/po.apiext.js'

const moduleName = 'po'
const headerSectionName = 'header'
const headerTableName = 'public.po' 
const headerPrimaryKey = 'po_id' 
const itemTableName = 'public.poitem'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await po_init(this, body) }

	// extender call
	async execute(body) { return await po_execute(this, body) }

	// header
	async headerList(body) { return await po_headerList(this, body) }
	async headerOpen(body) { return await po_headerOpen(this, body) }
	async headerUpdate(body) { return await po_headerUpdate(this, body)}
	async headerCreate(body) { return await po_headerCreate(this, body)}
	async headerDelete(body) { return await po_headerDelete(this, body) }

	
	// item	
	async itemList(body) { return await po_itemList(this, body) }
	async itemOpen(body) { return await po_itemOpen(this, body) }
	async itemUpdate(body) { return await po_itemUpdate(this, body)}
	async itemCreate(body) { return await po_itemCreate(this, body) }
	async itemDelete(body) { return await po_itemDelete(this, body) }
	async itemDeleteRows(body) { return await po_itemDeleteRows(this, body) }
			
}	

// init module
async function po_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.po_init === 'function') {
			// export async function po_init(self, initialData) {}
			await Extender.po_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function po_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, po_log) {}
		return await Extender[fnName](self, db, body, po_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function po_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function po_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `po_doc = \${searchtext} OR po_descr ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.po.partner_id)
			if (row.partner_id !== undefined) {
				const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', row.partner_id)
				row.partner_name = partner_name ?? null
			}
			// lookup: tax_value dari field tax_value pada table public.tax dimana (public.tax.tax_id = public.po.tax_id)
			if (row.tax_id !== undefined) {
				const { tax_value } = await sqlUtil.lookupdb(db, 'public.tax', 'tax_id', row.tax_id)
				row.tax_value = tax_value ?? null
			}
			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.po.brand_id)
			if (row.brand_id !== undefined) {
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name ?? null
			}
			// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.po.sea_id)
			if (row.sea_id !== undefined) {
				const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', row.sea_id)
				row.sea_name = sea_name ?? null
			}
			// lookup: curr_name dari field curr_name pada table public.curr dimana (public.curr.curr_id = public.po.curr_id)
			if (row.curr_id !== undefined) {
				const { curr_name } = await sqlUtil.lookupdb(db, 'public.curr', 'curr_id', row.curr_id)
				row.curr_name = curr_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function po_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { po_id: id }
		const searchMap = { po_id: `po_id = \${po_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.po.partner_id)
		if (data.partner_id !== undefined) {
			const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', data.partner_id)
			data.partner_name = partner_name ?? null
		}
		// lookup: tax_value dari field tax_value pada table public.tax dimana (public.tax.tax_id = public.po.tax_id)
		if (data.tax_id !== undefined) {
			const { tax_value } = await sqlUtil.lookupdb(db, 'public.tax', 'tax_id', data.tax_id)
			data.tax_value = tax_value ?? null
		}
		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.po.brand_id)
		if (data.brand_id !== undefined) {
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name ?? null
		}
		// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.po.sea_id)
		if (data.sea_id !== undefined) {
			const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', data.sea_id)
			data.sea_name = sea_name ?? null
		}
		// lookup: curr_name dari field curr_name pada table public.curr dimana (public.curr.curr_id = public.po.curr_id)
		if (data.curr_id !== undefined) {
			const { curr_name } = await sqlUtil.lookupdb(db, 'public.curr', 'curr_id', data.curr_id)
			data.curr_name = curr_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function po_headerCreate(self, body) {
	const { source='po', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'PO' }

			// buat sequencer document	
			const sequencer = createSequencerDocument(tx, { 
				COMPANY_CODE: req.app.locals.appConfig.COMPANY_CODE,
				blockLength: 3,
				numberLength: 6,
			})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate data sesuai prefix dari doc_id (default:  PO) reset pertahun
			const seqdata = await sequencer.yearly(args.doc_id)	
			data.po_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}			
			
			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			po_log(self, body, startTime, tablename, ret.po_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function po_headerUpdate(self, body) {
	const { source='po', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['po_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			po_log(self, body, startTime, tablename, data.po_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function po_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {po_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data item
			{
				const sql = `select * from ${itemTableName} where po_id=\${po_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowitem of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.itemDeleting === 'function') {
						// export async function itemDeleting(self, tx, rowitem, logMetadata) {}
						await Extender.itemDeleting(self, tx, rowitem, logMetadata)
					}

					const param = {poitem_id: rowitem.poitem_id}
					const cmd = sqlUtil.createDeleteCommand(itemTableName, ['poitem_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.itemDeleted === 'function') {
						// export async function itemDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.itemDeleted(self, tx, deletedRow, logMetadata)
					}					

					po_log(self, body, startTime, itemTableName, rowitem.poitem_id, 'DELETE', {rowdata: deletedRow})
					po_log(self, body, startTime, headerTableName, rowitem.po_id, 'DELETE ROW ITEM', {poitem_id: rowitem.poitem_id, tablename: itemTableName}, `removed: ${rowitem.poitem_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['po_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			po_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// item	

async function po_itemList(self, body) {
	const tablename = itemTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		po_id: `po_id=try_cast_bigint(\${po_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.poitem_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.itemListCriteria === 'function') {
			// export async function itemListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.itemListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: sku_code dari field sku_code pada table public.sku dimana (public.sku.sku_id = public.po.sku_id)
			if (row.sku_id !== undefined) {
				const { sku_code } = await sqlUtil.lookupdb(db, 'public.sku', 'sku_id', row.sku_id)
				row.sku_code = sku_code ?? null
			}
			// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.po.uom_id)
			if (row.uom_id !== undefined) {
				const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', row.uom_id)
				row.uom_name = uom_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function po_itemOpen(self, body) {
	const tablename = itemTableName

	try {
		const { id } = body 
		const criteria = { poitem_id: id }
		const searchMap = { poitem_id: `poitem_id = \${poitem_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: sku_code dari field sku_code pada table public.sku dimana (public.sku.sku_id = public.po.sku_id)
		if (data.sku_id !== undefined) {
			const { sku_code } = await sqlUtil.lookupdb(db, 'public.sku', 'sku_id', data.sku_id)
			data.sku_code = sku_code ?? null
		}
		// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.po.uom_id)
		if (data.uom_id !== undefined) {
			const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', data.uom_id)
			data.uom_name = uom_name ?? null
		}
		  
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function itemOpen(self, db, data) {}
		if (typeof Extender.itemOpen === 'function') {
			// export async function itemOpen(self, db, data) {}
			await Extender.itemOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function po_itemCreate(self, body) {
	const { source='po', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = itemTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'item', 
				doc_id: 'PO'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.poitem_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.itemCreating === 'function') {
				// export async function itemCreating(self, tx, data, seqdata, args) {}
				await Extender.itemCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.po_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.itemCreated === 'function') {
				// export async function itemCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.itemCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			po_log(self, body, startTime, tablename, ret.poitem_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function po_itemUpdate(self, body) {
	const { source='po', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = itemTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {poitem_id: data.poitem_id}
			const sql = `select * from ${itemTableName} where poitem_id=\${poitem_id}`
			const rowitem = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.itemUpdating === 'function') {
				// export async function itemUpdating(self, tx, data) {}
				await Extender.itemUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['poitem_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowitem.po_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.itemUpdated === 'function') {
				// export async function itemUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.itemUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			po_log(self, body, startTime, tablename, data.poitem_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function po_itemDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = itemTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {poitem_id: id}
			const sql = `select * from ${itemTableName} where poitem_id=\${poitem_id}`
			const rowitem = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.itemDeleting === 'function') {
				// export async function itemDeleting(self, tx, rowitem, logMetadata) {}
				await Extender.itemDeleting(self, tx, rowitem, logMetadata)
			}

			const param = {poitem_id: rowitem.poitem_id}
			const cmd = sqlUtil.createDeleteCommand(itemTableName, ['poitem_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowitem.po_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.itemDeleted === 'function') {
				// export async function itemDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.itemDeleted(self, tx, deletedRow, logMetadata)
			}					

			po_log(self, body, startTime, itemTableName, rowitem.poitem_id, 'DELETE', {rowdata: deletedRow})
			po_log(self, body, startTime, headerTableName, rowitem.po_id, 'DELETE ROW ITEM', {poitem_id: rowitem.poitem_id, tablename: itemTableName}, `removed: ${rowitem.poitem_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function po_itemDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = itemTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let po_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {poitem_id: id}
				const sql = `select * from ${itemTableName} where poitem_id=\${poitem_id}`
				const rowitem = await tx.oneOrNone(sql, dataToRemove)
				po_id = rowitem.po_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.itemDeleting === 'function') {
					// async function itemDeleting(self, tx, rowitem, logMetadata) {}
					await Extender.itemDeleting(self, tx, rowitem, logMetadata)
				}

				const param = {poitem_id: rowitem.poitem_id}
				const cmd = sqlUtil.createDeleteCommand(itemTableName, ['poitem_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowitem.po_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.itemDeleted === 'function') {
					// export async function itemDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.itemDeleted(self, tx, deletedRow, logMetadata)
				}					

				po_log(self, body, startTime, itemTableName, rowitem.poitem_id, 'DELETE', {rowdata: deletedRow})
				po_log(self, body, startTime, headerTableName, rowitem.po_id, 'DELETE ROW ITEM', {poitem_id: rowitem.poitem_id, tablename: itemTableName}, `removed: ${rowitem.poitem_id}`)
			}
		})
		

		const res = {
			deleted: true,
			po_id: po_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'itemRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function itemRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	