/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/productmodel.apiext.js'

const moduleName = 'productmodel'
const headerSectionName = 'header'
const headerTableName = 'public.model' 
const headerPrimaryKey = 'model_id' 
const propTableName = 'public.modelprop'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await productmodel_init(this, body) }

	// extender call
	async execute(body) { return await productmodel_execute(this, body) }

	// header
	async headerList(body) { return await productmodel_headerList(this, body) }
	async headerOpen(body) { return await productmodel_headerOpen(this, body) }
	async headerUpdate(body) { return await productmodel_headerUpdate(this, body)}
	async headerCreate(body) { return await productmodel_headerCreate(this, body)}
	async headerDelete(body) { return await productmodel_headerDelete(this, body) }

	
	// prop	
	async propList(body) { return await productmodel_propList(this, body) }
	async propOpen(body) { return await productmodel_propOpen(this, body) }
	async propUpdate(body) { return await productmodel_propUpdate(this, body)}
	async propCreate(body) { return await productmodel_propCreate(this, body) }
	async propDelete(body) { return await productmodel_propDelete(this, body) }
	async propDeleteRows(body) { return await productmodel_propDeleteRows(this, body) }
			
}	

// init module
async function productmodel_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.productmodel_init === 'function') {
			// export async function productmodel_init(self, initialData) {}
			await Extender.productmodel_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function productmodel_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, productmodel_log) {}
		return await Extender[fnName](self, db, body, productmodel_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function productmodel_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function productmodel_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `model_id=try_cast_int(\${searchtext}, 0) OR model_name ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.model.variancetype_id)
			if (row.variancetype_id !== undefined) {
				const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', row.variancetype_id)
				row.variancetype_name = variancetype_name ?? null
			}
			// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.model.skuopt_id)
			if (row.skuopt_id !== undefined) {
				const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', row.skuopt_id)
				row.skuopt_name = skuopt_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function productmodel_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { model_id: id }
		const searchMap = { model_id: `model_id = \${model_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.model.variancetype_id)
		if (data.variancetype_id !== undefined) {
			const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', data.variancetype_id)
			data.variancetype_name = variancetype_name ?? null
		}
		// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.model.skuopt_id)
		if (data.skuopt_id !== undefined) {
			const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', data.skuopt_id)
			data.skuopt_name = skuopt_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function productmodel_headerCreate(self, body) {
	const { source='productmodel', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data, ['model_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			productmodel_log(self, body, startTime, tablename, ret.model_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function productmodel_headerUpdate(self, body) {
	const { source='productmodel', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['model_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			productmodel_log(self, body, startTime, tablename, data.model_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function productmodel_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {model_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data prop
			{
				const sql = `select * from ${propTableName} where model_id=\${model_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowprop of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.propDeleting === 'function') {
						// export async function propDeleting(self, tx, rowprop, logMetadata) {}
						await Extender.propDeleting(self, tx, rowprop, logMetadata)
					}

					const param = {modelprop_id: rowprop.modelprop_id}
					const cmd = sqlUtil.createDeleteCommand(propTableName, ['modelprop_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.propDeleted === 'function') {
						// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.propDeleted(self, tx, deletedRow, logMetadata)
					}					

					productmodel_log(self, body, startTime, propTableName, rowprop.modelprop_id, 'DELETE', {rowdata: deletedRow})
					productmodel_log(self, body, startTime, headerTableName, rowprop.model_id, 'DELETE ROW PROP', {modelprop_id: rowprop.modelprop_id, tablename: propTableName}, `removed: ${rowprop.modelprop_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['model_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			productmodel_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// prop	

async function productmodel_propList(self, body) {
	const tablename = propTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		model_id: `model_id=try_cast_bigint(\${model_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.modelprop_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.propListCriteria === 'function') {
			// export async function propListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.propListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: prop_name dari field prop_name pada table public.prop dimana (public.prop.prop_id = public.model.prop_id)
			if (row.prop_id !== undefined) {
				const { prop_name } = await sqlUtil.lookupdb(db, 'public.prop', 'prop_id', row.prop_id)
				row.prop_name = prop_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function productmodel_propOpen(self, body) {
	const tablename = propTableName

	try {
		const { id } = body 
		const criteria = { modelprop_id: id }
		const searchMap = { modelprop_id: `modelprop_id = \${modelprop_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: prop_name dari field prop_name pada table public.prop dimana (public.prop.prop_id = public.model.prop_id)
		if (data.prop_id !== undefined) {
			const { prop_name } = await sqlUtil.lookupdb(db, 'public.prop', 'prop_id', data.prop_id)
			data.prop_name = prop_name ?? null
		}
		  
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function propOpen(self, db, data) {}
		if (typeof Extender.propOpen === 'function') {
			// export async function propOpen(self, db, data) {}
			await Extender.propOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function productmodel_propCreate(self, body) {
	const { source='productmodel', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = propTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'prop', 
				doc_id: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.modelprop_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.propCreating === 'function') {
				// export async function propCreating(self, tx, data, seqdata, args) {}
				await Extender.propCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.model_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.propCreated === 'function') {
				// export async function propCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.propCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			productmodel_log(self, body, startTime, tablename, ret.modelprop_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function productmodel_propUpdate(self, body) {
	const { source='productmodel', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = propTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {modelprop_id: data.modelprop_id}
			const sql = `select * from ${propTableName} where modelprop_id=\${modelprop_id}`
			const rowprop = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.propUpdating === 'function') {
				// export async function propUpdating(self, tx, data) {}
				await Extender.propUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['modelprop_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowprop.model_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.propUpdated === 'function') {
				// export async function propUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.propUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			productmodel_log(self, body, startTime, tablename, data.modelprop_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function productmodel_propDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = propTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {modelprop_id: id}
			const sql = `select * from ${propTableName} where modelprop_id=\${modelprop_id}`
			const rowprop = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.propDeleting === 'function') {
				// export async function propDeleting(self, tx, rowprop, logMetadata) {}
				await Extender.propDeleting(self, tx, rowprop, logMetadata)
			}

			const param = {modelprop_id: rowprop.modelprop_id}
			const cmd = sqlUtil.createDeleteCommand(propTableName, ['modelprop_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowprop.model_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.propDeleted === 'function') {
				// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.propDeleted(self, tx, deletedRow, logMetadata)
			}					

			productmodel_log(self, body, startTime, propTableName, rowprop.modelprop_id, 'DELETE', {rowdata: deletedRow})
			productmodel_log(self, body, startTime, headerTableName, rowprop.model_id, 'DELETE ROW PROP', {modelprop_id: rowprop.modelprop_id, tablename: propTableName}, `removed: ${rowprop.modelprop_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function productmodel_propDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = propTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let model_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {modelprop_id: id}
				const sql = `select * from ${propTableName} where modelprop_id=\${modelprop_id}`
				const rowprop = await tx.oneOrNone(sql, dataToRemove)
				model_id = rowprop.model_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.propDeleting === 'function') {
					// async function propDeleting(self, tx, rowprop, logMetadata) {}
					await Extender.propDeleting(self, tx, rowprop, logMetadata)
				}

				const param = {modelprop_id: rowprop.modelprop_id}
				const cmd = sqlUtil.createDeleteCommand(propTableName, ['modelprop_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowprop.model_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.propDeleted === 'function') {
					// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.propDeleted(self, tx, deletedRow, logMetadata)
				}					

				productmodel_log(self, body, startTime, propTableName, rowprop.modelprop_id, 'DELETE', {rowdata: deletedRow})
				productmodel_log(self, body, startTime, headerTableName, rowprop.model_id, 'DELETE ROW PROP', {modelprop_id: rowprop.modelprop_id, tablename: propTableName}, `removed: ${rowprop.modelprop_id}`)
			}
		})
		

		const res = {
			deleted: true,
			model_id: model_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'propRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function propRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	