/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/product.apiext.js'

const moduleName = 'product'
const headerSectionName = 'header'
const headerTableName = 'public.product' 
const headerPrimaryKey = 'product_id' 
const varianceTableName = 'public.variance'  
const propTableName = 'public.productprop'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await product_init(this, body) }

	// extender call
	async execute(body) { return await product_execute(this, body) }

	// header
	async headerList(body) { return await product_headerList(this, body) }
	async headerOpen(body) { return await product_headerOpen(this, body) }
	async headerUpdate(body) { return await product_headerUpdate(this, body)}
	async headerCreate(body) { return await product_headerCreate(this, body)}
	async headerDelete(body) { return await product_headerDelete(this, body) }

	
	// variance	
	async varianceList(body) { return await product_varianceList(this, body) }
	async varianceOpen(body) { return await product_varianceOpen(this, body) }
	async varianceUpdate(body) { return await product_varianceUpdate(this, body)}
	async varianceCreate(body) { return await product_varianceCreate(this, body) }
	async varianceDelete(body) { return await product_varianceDelete(this, body) }
	async varianceDeleteRows(body) { return await product_varianceDeleteRows(this, body) }
	
	// prop	
	async propList(body) { return await product_propList(this, body) }
	async propOpen(body) { return await product_propOpen(this, body) }
	async propUpdate(body) { return await product_propUpdate(this, body)}
	async propCreate(body) { return await product_propCreate(this, body) }
	async propDelete(body) { return await product_propDelete(this, body) }
	async propDeleteRows(body) { return await product_propDeleteRows(this, body) }
			
}	

// init module
async function product_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.product_init === 'function') {
			// export async function product_init(self, initialData) {}
			await Extender.product_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function product_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, product_log) {}
		return await Extender[fnName](self, db, body, product_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function product_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function product_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `product_code = \${searchtext} OR product_name ILIKE '%' || \${searchtext} || '%'`,
		brand_id: `brand_id=try_cast_int(\${brand_id}, 0)`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: model_name dari field model_name pada table public.model dimana (public.model.model_id = public.product.model_id)
			if (row.model_id !== undefined) {
				const { model_name } = await sqlUtil.lookupdb(db, 'public.model', 'model_id', row.model_id)
				row.model_name = model_name ?? null
			}
			// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.product.uom_id)
			if (row.uom_id !== undefined) {
				const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', row.uom_id)
				row.uom_name = uom_name ?? null
			}
			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.product.brand_id)
			if (row.brand_id !== undefined) {
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name ?? null
			}
			// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.product.variancetype_id)
			if (row.variancetype_id !== undefined) {
				const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', row.variancetype_id)
				row.variancetype_name = variancetype_name ?? null
			}
			// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.product.skuopt)
			if (row.skuopt !== undefined) {
				const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', row.skuopt)
				row.skuopt_name = skuopt_name ?? null
			}
			// lookup: gro_name dari field gro_name pada table public.gro dimana (public.gro.gro_id = public.product.gro_id)
			if (row.gro_id !== undefined) {
				const { gro_name } = await sqlUtil.lookupdb(db, 'public.gro', 'gro_id', row.gro_id)
				row.gro_name = gro_name ?? null
			}
			// lookup: ctg_name dari field ctg_name pada table public.ctg dimana (public.ctg.ctg_id = public.product.ctg_id)
			if (row.ctg_id !== undefined) {
				const { ctg_name } = await sqlUtil.lookupdb(db, 'public.ctg', 'ctg_id', row.ctg_id)
				row.ctg_name = ctg_name ?? null
			}
			// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.product.sea_id)
			if (row.sea_id !== undefined) {
				const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', row.sea_id)
				row.sea_name = sea_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function product_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { product_id: id }
		const searchMap = { product_id: `product_id = \${product_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: model_name dari field model_name pada table public.model dimana (public.model.model_id = public.product.model_id)
		if (data.model_id !== undefined) {
			const { model_name } = await sqlUtil.lookupdb(db, 'public.model', 'model_id', data.model_id)
			data.model_name = model_name ?? null
		}
		// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.product.uom_id)
		if (data.uom_id !== undefined) {
			const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', data.uom_id)
			data.uom_name = uom_name ?? null
		}
		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.product.brand_id)
		if (data.brand_id !== undefined) {
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name ?? null
		}
		// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.product.variancetype_id)
		if (data.variancetype_id !== undefined) {
			const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', data.variancetype_id)
			data.variancetype_name = variancetype_name ?? null
		}
		// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.product.skuopt)
		if (data.skuopt !== undefined) {
			const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', data.skuopt)
			data.skuopt_name = skuopt_name ?? null
		}
		// lookup: gro_name dari field gro_name pada table public.gro dimana (public.gro.gro_id = public.product.gro_id)
		if (data.gro_id !== undefined) {
			const { gro_name } = await sqlUtil.lookupdb(db, 'public.gro', 'gro_id', data.gro_id)
			data.gro_name = gro_name ?? null
		}
		// lookup: ctg_name dari field ctg_name pada table public.ctg dimana (public.ctg.ctg_id = public.product.ctg_id)
		if (data.ctg_id !== undefined) {
			const { ctg_name } = await sqlUtil.lookupdb(db, 'public.ctg', 'ctg_id', data.ctg_id)
			data.ctg_name = ctg_name ?? null
		}
		// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.product.sea_id)
		if (data.sea_id !== undefined) {
			const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', data.sea_id)
			data.sea_name = sea_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function product_headerCreate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

			
			// buat short sequencer	
			const sequencer = createSequencerLine(tx, {})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate short id sesuai prefix (default: ) reset pertahun
			const seqdata = await sequencer.yearlyshort(args.doc_id)
			data.product_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}

			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			product_log(self, body, startTime, tablename, ret.product_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function product_headerUpdate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['product_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			product_log(self, body, startTime, tablename, data.product_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function product_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {product_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data variance
			{
				const sql = `select * from ${varianceTableName} where product_id=\${product_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowvariance of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.varianceDeleting === 'function') {
						// export async function varianceDeleting(self, tx, rowvariance, logMetadata) {}
						await Extender.varianceDeleting(self, tx, rowvariance, logMetadata)
					}

					const param = {variance_id: rowvariance.variance_id}
					const cmd = sqlUtil.createDeleteCommand(varianceTableName, ['variance_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.varianceDeleted === 'function') {
						// export async function varianceDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.varianceDeleted(self, tx, deletedRow, logMetadata)
					}					

					product_log(self, body, startTime, varianceTableName, rowvariance.variance_id, 'DELETE', {rowdata: deletedRow})
					product_log(self, body, startTime, headerTableName, rowvariance.product_id, 'DELETE ROW VARIANCE', {variance_id: rowvariance.variance_id, tablename: varianceTableName}, `removed: ${rowvariance.variance_id}`)


				}	
			}

			// hapus data prop
			{
				const sql = `select * from ${propTableName} where product_id=\${product_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowprop of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.propDeleting === 'function') {
						// export async function propDeleting(self, tx, rowprop, logMetadata) {}
						await Extender.propDeleting(self, tx, rowprop, logMetadata)
					}

					const param = {productprop_id: rowprop.productprop_id}
					const cmd = sqlUtil.createDeleteCommand(propTableName, ['productprop_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.propDeleted === 'function') {
						// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.propDeleted(self, tx, deletedRow, logMetadata)
					}					

					product_log(self, body, startTime, propTableName, rowprop.productprop_id, 'DELETE', {rowdata: deletedRow})
					product_log(self, body, startTime, headerTableName, rowprop.product_id, 'DELETE ROW PROP', {productprop_id: rowprop.productprop_id, tablename: propTableName}, `removed: ${rowprop.productprop_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['product_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			product_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// variance	

async function product_varianceList(self, body) {
	const tablename = varianceTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		product_id: `product_id=try_cast_bigint(\${product_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.variance_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.varianceListCriteria === 'function') {
			// export async function varianceListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.varianceListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			 
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function product_varianceOpen(self, body) {
	const tablename = varianceTableName

	try {
		const { id } = body 
		const criteria = { variance_id: id }
		const searchMap = { variance_id: `variance_id = \${variance_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		  
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function varianceOpen(self, db, data) {}
		if (typeof Extender.varianceOpen === 'function') {
			// export async function varianceOpen(self, db, data) {}
			await Extender.varianceOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function product_varianceCreate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = varianceTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'variance', 
				doc_id: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.variance_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.varianceCreating === 'function') {
				// export async function varianceCreating(self, tx, data, seqdata, args) {}
				await Extender.varianceCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.product_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.varianceCreated === 'function') {
				// export async function varianceCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.varianceCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			product_log(self, body, startTime, tablename, ret.variance_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function product_varianceUpdate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = varianceTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {variance_id: data.variance_id}
			const sql = `select * from ${varianceTableName} where variance_id=\${variance_id}`
			const rowvariance = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.varianceUpdating === 'function') {
				// export async function varianceUpdating(self, tx, data) {}
				await Extender.varianceUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['variance_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowvariance.product_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.varianceUpdated === 'function') {
				// export async function varianceUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.varianceUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			product_log(self, body, startTime, tablename, data.variance_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function product_varianceDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = varianceTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {variance_id: id}
			const sql = `select * from ${varianceTableName} where variance_id=\${variance_id}`
			const rowvariance = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.varianceDeleting === 'function') {
				// export async function varianceDeleting(self, tx, rowvariance, logMetadata) {}
				await Extender.varianceDeleting(self, tx, rowvariance, logMetadata)
			}

			const param = {variance_id: rowvariance.variance_id}
			const cmd = sqlUtil.createDeleteCommand(varianceTableName, ['variance_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowvariance.product_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.varianceDeleted === 'function') {
				// export async function varianceDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.varianceDeleted(self, tx, deletedRow, logMetadata)
			}					

			product_log(self, body, startTime, varianceTableName, rowvariance.variance_id, 'DELETE', {rowdata: deletedRow})
			product_log(self, body, startTime, headerTableName, rowvariance.product_id, 'DELETE ROW VARIANCE', {variance_id: rowvariance.variance_id, tablename: varianceTableName}, `removed: ${rowvariance.variance_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function product_varianceDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = varianceTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let product_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {variance_id: id}
				const sql = `select * from ${varianceTableName} where variance_id=\${variance_id}`
				const rowvariance = await tx.oneOrNone(sql, dataToRemove)
				product_id = rowvariance.product_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.varianceDeleting === 'function') {
					// async function varianceDeleting(self, tx, rowvariance, logMetadata) {}
					await Extender.varianceDeleting(self, tx, rowvariance, logMetadata)
				}

				const param = {variance_id: rowvariance.variance_id}
				const cmd = sqlUtil.createDeleteCommand(varianceTableName, ['variance_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowvariance.product_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.varianceDeleted === 'function') {
					// export async function varianceDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.varianceDeleted(self, tx, deletedRow, logMetadata)
				}					

				product_log(self, body, startTime, varianceTableName, rowvariance.variance_id, 'DELETE', {rowdata: deletedRow})
				product_log(self, body, startTime, headerTableName, rowvariance.product_id, 'DELETE ROW VARIANCE', {variance_id: rowvariance.variance_id, tablename: varianceTableName}, `removed: ${rowvariance.variance_id}`)
			}
		})
		

		const res = {
			deleted: true,
			product_id: product_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'varianceRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function varianceRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}


// prop	

async function product_propList(self, body) {
	const tablename = propTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		product_id: `product_id=try_cast_bigint(\${product_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.productprop_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.propListCriteria === 'function') {
			// export async function propListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.propListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: prop_name dari field prop_name pada table public.prop dimana (public.prop.prop_id = public.product.prop_id)
			if (row.prop_id !== undefined) {
				const { prop_name } = await sqlUtil.lookupdb(db, 'public.prop', 'prop_id', row.prop_id)
				row.prop_name = prop_name ?? null
			}
			 
			// field dengan tipedata json/jsonb	
			{
				if (row.prop_data) {
					row.prop_data = JSON.stringify(row.prop_data)
				}
			}
			
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function product_propOpen(self, body) {
	const tablename = propTableName

	try {
		const { id } = body 
		const criteria = { productprop_id: id }
		const searchMap = { productprop_id: `productprop_id = \${productprop_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: prop_name dari field prop_name pada table public.prop dimana (public.prop.prop_id = public.product.prop_id)
		if (data.prop_id !== undefined) {
			const { prop_name } = await sqlUtil.lookupdb(db, 'public.prop', 'prop_id', data.prop_id)
			data.prop_name = prop_name ?? null
		}
		  
		// field dengan tipedata json/jsonb	
		{
			if (data.prop_data) {
				data.prop_data = JSON.stringify(data.prop_data)
			}
		}
		
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function propOpen(self, db, data) {}
		if (typeof Extender.propOpen === 'function') {
			// export async function propOpen(self, db, data) {}
			await Extender.propOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function product_propCreate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = propTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'prop', 
				doc_id: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.productprop_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.propCreating === 'function') {
				// export async function propCreating(self, tx, data, seqdata, args) {}
				await Extender.propCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.product_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.propCreated === 'function') {
				// export async function propCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.propCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			product_log(self, body, startTime, tablename, ret.productprop_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function product_propUpdate(self, body) {
	const { source='product', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = propTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {productprop_id: data.productprop_id}
			const sql = `select * from ${propTableName} where productprop_id=\${productprop_id}`
			const rowprop = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.propUpdating === 'function') {
				// export async function propUpdating(self, tx, data) {}
				await Extender.propUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['productprop_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowprop.product_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.propUpdated === 'function') {
				// export async function propUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.propUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			product_log(self, body, startTime, tablename, data.productprop_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function product_propDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = propTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {productprop_id: id}
			const sql = `select * from ${propTableName} where productprop_id=\${productprop_id}`
			const rowprop = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.propDeleting === 'function') {
				// export async function propDeleting(self, tx, rowprop, logMetadata) {}
				await Extender.propDeleting(self, tx, rowprop, logMetadata)
			}

			const param = {productprop_id: rowprop.productprop_id}
			const cmd = sqlUtil.createDeleteCommand(propTableName, ['productprop_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowprop.product_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.propDeleted === 'function') {
				// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.propDeleted(self, tx, deletedRow, logMetadata)
			}					

			product_log(self, body, startTime, propTableName, rowprop.productprop_id, 'DELETE', {rowdata: deletedRow})
			product_log(self, body, startTime, headerTableName, rowprop.product_id, 'DELETE ROW PROP', {productprop_id: rowprop.productprop_id, tablename: propTableName}, `removed: ${rowprop.productprop_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function product_propDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = propTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let product_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {productprop_id: id}
				const sql = `select * from ${propTableName} where productprop_id=\${productprop_id}`
				const rowprop = await tx.oneOrNone(sql, dataToRemove)
				product_id = rowprop.product_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.propDeleting === 'function') {
					// async function propDeleting(self, tx, rowprop, logMetadata) {}
					await Extender.propDeleting(self, tx, rowprop, logMetadata)
				}

				const param = {productprop_id: rowprop.productprop_id}
				const cmd = sqlUtil.createDeleteCommand(propTableName, ['productprop_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowprop.product_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.propDeleted === 'function') {
					// export async function propDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.propDeleted(self, tx, deletedRow, logMetadata)
				}					

				product_log(self, body, startTime, propTableName, rowprop.productprop_id, 'DELETE', {rowdata: deletedRow})
				product_log(self, body, startTime, headerTableName, rowprop.product_id, 'DELETE ROW PROP', {productprop_id: rowprop.productprop_id, tablename: propTableName}, `removed: ${rowprop.productprop_id}`)
			}
		})
		

		const res = {
			deleted: true,
			product_id: product_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'propRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function propRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	