/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/sea.apiext.js'

const moduleName = 'sea'
const headerSectionName = 'header'
const headerTableName = 'public.sea' 
const headerPrimaryKey = 'sea_id' 
const refTableName = 'public.searef'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await sea_init(this, body) }

	// extender call
	async execute(body) { return await sea_execute(this, body) }

	// header
	async headerList(body) { return await sea_headerList(this, body) }
	async headerOpen(body) { return await sea_headerOpen(this, body) }
	async headerUpdate(body) { return await sea_headerUpdate(this, body)}
	async headerCreate(body) { return await sea_headerCreate(this, body)}
	async headerDelete(body) { return await sea_headerDelete(this, body) }

	
	// ref	
	async refList(body) { return await sea_refList(this, body) }
	async refOpen(body) { return await sea_refOpen(this, body) }
	async refUpdate(body) { return await sea_refUpdate(this, body)}
	async refCreate(body) { return await sea_refCreate(this, body) }
	async refDelete(body) { return await sea_refDelete(this, body) }
	async refDeleteRows(body) { return await sea_refDeleteRows(this, body) }
			
}	

// init module
async function sea_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.sea_init === 'function') {
			// export async function sea_init(self, initialData) {}
			await Extender.sea_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function sea_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, sea_log) {}
		return await Extender[fnName](self, db, body, sea_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function sea_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function sea_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `sea_id = \${searchtext} OR sea_name ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: seagro_name dari field seagro_name pada table public.seagro dimana (public.seagro.seagro_id = public.sea.seagro_id)
			if (row.seagro_id !== undefined) {
				const { seagro_name } = await sqlUtil.lookupdb(db, 'public.seagro', 'seagro_id', row.seagro_id)
				row.seagro_name = seagro_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function sea_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { sea_id: id }
		const searchMap = { sea_id: `sea_id = \${sea_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: seagro_name dari field seagro_name pada table public.seagro dimana (public.seagro.seagro_id = public.sea.seagro_id)
		if (data.seagro_id !== undefined) {
			const { seagro_name } = await sqlUtil.lookupdb(db, 'public.seagro', 'seagro_id', data.seagro_id)
			data.seagro_name = seagro_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function sea_headerCreate(self, body) {
	const { source='sea', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			sea_log(self, body, startTime, tablename, ret.sea_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function sea_headerUpdate(self, body) {
	const { source='sea', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['sea_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			sea_log(self, body, startTime, tablename, data.sea_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function sea_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {sea_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data ref
			{
				const sql = `select * from ${refTableName} where sea_id=\${sea_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowref of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.refDeleting === 'function') {
						// export async function refDeleting(self, tx, rowref, logMetadata) {}
						await Extender.refDeleting(self, tx, rowref, logMetadata)
					}

					const param = {searef_id: rowref.searef_id}
					const cmd = sqlUtil.createDeleteCommand(refTableName, ['searef_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.refDeleted === 'function') {
						// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.refDeleted(self, tx, deletedRow, logMetadata)
					}					

					sea_log(self, body, startTime, refTableName, rowref.searef_id, 'DELETE', {rowdata: deletedRow})
					sea_log(self, body, startTime, headerTableName, rowref.sea_id, 'DELETE ROW REF', {searef_id: rowref.searef_id, tablename: refTableName}, `removed: ${rowref.searef_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['sea_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			sea_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// ref	

async function sea_refList(self, body) {
	const tablename = refTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		sea_id: `sea_id=try_cast_bigint(\${sea_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.searef_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.refListCriteria === 'function') {
			// export async function refListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.refListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: interface_name dari field interface_name pada table core.interface dimana (core.interface.interface_id = public.sea.interface_id)
			if (row.interface_id !== undefined) {
				const { interface_name } = await sqlUtil.lookupdb(db, 'core.interface', 'interface_id', row.interface_id)
				row.interface_name = interface_name ?? null
			}
			 
			// field dengan tipedata json/jsonb	
			{
				if (row.ref_data) {
					row.ref_data = JSON.stringify(row.ref_data)
				}
			}
			
			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function sea_refOpen(self, body) {
	const tablename = refTableName

	try {
		const { id } = body 
		const criteria = { searef_id: id }
		const searchMap = { searef_id: `searef_id = \${searef_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: interface_name dari field interface_name pada table core.interface dimana (core.interface.interface_id = public.sea.interface_id)
		if (data.interface_id !== undefined) {
			const { interface_name } = await sqlUtil.lookupdb(db, 'core.interface', 'interface_id', data.interface_id)
			data.interface_name = interface_name ?? null
		}
		  
		// field dengan tipedata json/jsonb	
		{
			if (data.ref_data) {
				data.ref_data = JSON.stringify(data.ref_data)
			}
		}
		
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function refOpen(self, db, data) {}
		if (typeof Extender.refOpen === 'function') {
			// export async function refOpen(self, db, data) {}
			await Extender.refOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function sea_refCreate(self, body) {
	const { source='sea', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = refTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'ref', 
				doc_id: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.doc_id)
			data.searef_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.refCreating === 'function') {
				// export async function refCreating(self, tx, data, seqdata, args) {}
				await Extender.refCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: data.sea_id
			})


			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.refCreated === 'function') {
				// export async function refCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.refCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			sea_log(self, body, startTime, tablename, ret.searef_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function sea_refUpdate(self, body) {
	const { source='sea', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = refTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToUpdate = {searef_id: data.searef_id}
			const sql = `select * from ${refTableName} where searef_id=\${searef_id}`
			const rowref = await tx.oneOrNone(sql, dataToUpdate)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.refUpdating === 'function') {
				// export async function refUpdating(self, tx, data) {}
				await Extender.refUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['searef_id'])
			const ret = await cmd.execute(data)
			

			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowref.sea_id
			})

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.refUpdated === 'function') {
				// export async function refUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.refUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			sea_log(self, body, startTime, tablename, data.searef_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function sea_refDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = refTableName

	try {

		const data_timestamp = (new Date()).toISOString()

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {searef_id: id}
			const sql = `select * from ${refTableName} where searef_id=\${searef_id}`
			const rowref = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.refDeleting === 'function') {
				// export async function refDeleting(self, tx, rowref, logMetadata) {}
				await Extender.refDeleting(self, tx, rowref, logMetadata)
			}

			const param = {searef_id: rowref.searef_id}
			const cmd = sqlUtil.createDeleteCommand(refTableName, ['searef_id'])
			const deletedRow = await cmd.execute(param)


			// update timestamp pada header
			tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
				_timestamp: data_timestamp,
				pk: rowref.sea_id
			})

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.refDeleted === 'function') {
				// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.refDeleted(self, tx, deletedRow, logMetadata)
			}					

			sea_log(self, body, startTime, refTableName, rowref.searef_id, 'DELETE', {rowdata: deletedRow})
			sea_log(self, body, startTime, headerTableName, rowref.sea_id, 'DELETE ROW REF', {searef_id: rowref.searef_id, tablename: refTableName}, `removed: ${rowref.searef_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function sea_refDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = refTableName


	try {


		const data_timestamp = (new Date()).toISOString()

		let sea_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {searef_id: id}
				const sql = `select * from ${refTableName} where searef_id=\${searef_id}`
				const rowref = await tx.oneOrNone(sql, dataToRemove)
				sea_id = rowref.sea_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.refDeleting === 'function') {
					// async function refDeleting(self, tx, rowref, logMetadata) {}
					await Extender.refDeleting(self, tx, rowref, logMetadata)
				}

				const param = {searef_id: rowref.searef_id}
				const cmd = sqlUtil.createDeleteCommand(refTableName, ['searef_id'])
				const deletedRow = await cmd.execute(param)

				// update timestamp pada header
				tx.none(`update ${headerTableName} set _timestamp=$[_timestamp] where ${headerPrimaryKey}=$[pk]`, {
					_timestamp: data_timestamp,
					pk: rowref.sea_id
				})
				
				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.refDeleted === 'function') {
					// export async function refDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.refDeleted(self, tx, deletedRow, logMetadata)
				}					

				sea_log(self, body, startTime, refTableName, rowref.searef_id, 'DELETE', {rowdata: deletedRow})
				sea_log(self, body, startTime, headerTableName, rowref.sea_id, 'DELETE ROW REF', {searef_id: rowref.searef_id, tablename: refTableName}, `removed: ${rowref.searef_id}`)
			}
		})
		

		const res = {
			deleted: true,
			sea_id: sea_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'refRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function refRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	