/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import { getProgramSetting } from '@agung_dhewe/webapps/src/helper.js'
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/sku.apiext.js'

const moduleName = 'sku'
const headerSectionName = 'header'
const headerTableName = 'public.sku' 
const headerPrimaryKey = 'sku_id' 	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await sku_init(this, body) }

	// extender call
	async execute(body) { return await sku_execute(this, body) }

	// header
	async headerList(body) { return await sku_headerList(this, body) }
	async headerOpen(body) { return await sku_headerOpen(this, body) }
	async headerUpdate(body) { return await sku_headerUpdate(this, body)}
	async headerCreate(body) { return await sku_headerCreate(this, body)}
	async headerDelete(body) { return await sku_headerDelete(this, body) }

			
}	

// init module
async function sku_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const programName = req.params.modulename;
		const variance = req.query.variance;
		const programSetting = await getProgramSetting(db, programName, variance)
		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {
				program: programSetting
			}
		}
		
		if (typeof Extender.sku_init === 'function') {
			// export async function sku_init(self, initialData) {}
			await Extender.sku_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function sku_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, sku_log) {}
		return await Extender[fnName](self, db, body, sku_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function sku_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function sku_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `sku_id=try_cast_bigint(\${searchtext}, 0) OR sku_code = \${searchtext} OR sku_name ILIKE '%' || \${searchtext} || '%'`,
		brand_id: `brand_id=try_cast_int(\${brand_id}, 0)`,
		ctg_id: `ctg_id=try_cast_int(\${ctg_id}, 0)`,
		gro_id: `gro_id=try_cast_int(\${gro_id}, 0)`,
		sea_id: `sea_id = \${sea_id}`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.sku.brand_id)
			if (row.brand_id !== undefined) {
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name ?? null
			}
			// lookup: product_name dari field product_name pada table public.product dimana (public.product.product_id = public.sku.product_id)
			if (row.product_id !== undefined) {
				const { product_name } = await sqlUtil.lookupdb(db, 'public.product', 'product_id', row.product_id)
				row.product_name = product_name ?? null
			}
			// lookup: model_name dari field model_name pada table public.model dimana (public.model.model_id = public.sku.model_id)
			if (row.model_id !== undefined) {
				const { model_name } = await sqlUtil.lookupdb(db, 'public.model', 'model_id', row.model_id)
				row.model_name = model_name ?? null
			}
			// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.sku.variancetype_id)
			if (row.variancetype_id !== undefined) {
				const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', row.variancetype_id)
				row.variancetype_name = variancetype_name ?? null
			}
			// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.sku.skuopt_id)
			if (row.skuopt_id !== undefined) {
				const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', row.skuopt_id)
				row.skuopt_name = skuopt_name ?? null
			}
			// lookup: gro_name dari field gro_name pada table public.gro dimana (public.gro.gro_id = public.sku.gro_id)
			if (row.gro_id !== undefined) {
				const { gro_name } = await sqlUtil.lookupdb(db, 'public.gro', 'gro_id', row.gro_id)
				row.gro_name = gro_name ?? null
			}
			// lookup: ctg_name dari field ctg_name pada table public.ctg dimana (public.ctg.ctg_id = public.sku.ctg_id)
			if (row.ctg_id !== undefined) {
				const { ctg_name } = await sqlUtil.lookupdb(db, 'public.ctg', 'ctg_id', row.ctg_id)
				row.ctg_name = ctg_name ?? null
			}
			// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.sku.uom_id)
			if (row.uom_id !== undefined) {
				const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', row.uom_id)
				row.uom_name = uom_name ?? null
			}
			// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.sku.sea_id)
			if (row.sea_id !== undefined) {
				const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', row.sea_id)
				row.sea_name = sea_name ?? null
			}
			 
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function sku_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { sku_id: id }
		const searchMap = { sku_id: `sku_id = \${sku_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.sku.brand_id)
		if (data.brand_id !== undefined) {
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name ?? null
		}
		// lookup: product_name dari field product_name pada table public.product dimana (public.product.product_id = public.sku.product_id)
		if (data.product_id !== undefined) {
			const { product_name } = await sqlUtil.lookupdb(db, 'public.product', 'product_id', data.product_id)
			data.product_name = product_name ?? null
		}
		// lookup: model_name dari field model_name pada table public.model dimana (public.model.model_id = public.sku.model_id)
		if (data.model_id !== undefined) {
			const { model_name } = await sqlUtil.lookupdb(db, 'public.model', 'model_id', data.model_id)
			data.model_name = model_name ?? null
		}
		// lookup: variancetype_name dari field variancetype_name pada table public.variancetype dimana (public.variancetype.variancetype_id = public.sku.variancetype_id)
		if (data.variancetype_id !== undefined) {
			const { variancetype_name } = await sqlUtil.lookupdb(db, 'public.variancetype', 'variancetype_id', data.variancetype_id)
			data.variancetype_name = variancetype_name ?? null
		}
		// lookup: skuopt_name dari field skuopt_name pada table public.skuopt dimana (public.skuopt.skuopt_id = public.sku.skuopt_id)
		if (data.skuopt_id !== undefined) {
			const { skuopt_name } = await sqlUtil.lookupdb(db, 'public.skuopt', 'skuopt_id', data.skuopt_id)
			data.skuopt_name = skuopt_name ?? null
		}
		// lookup: gro_name dari field gro_name pada table public.gro dimana (public.gro.gro_id = public.sku.gro_id)
		if (data.gro_id !== undefined) {
			const { gro_name } = await sqlUtil.lookupdb(db, 'public.gro', 'gro_id', data.gro_id)
			data.gro_name = gro_name ?? null
		}
		// lookup: ctg_name dari field ctg_name pada table public.ctg dimana (public.ctg.ctg_id = public.sku.ctg_id)
		if (data.ctg_id !== undefined) {
			const { ctg_name } = await sqlUtil.lookupdb(db, 'public.ctg', 'ctg_id', data.ctg_id)
			data.ctg_name = ctg_name ?? null
		}
		// lookup: uom_name dari field uom_name pada table public.uom dimana (public.uom.uom_id = public.sku.uom_id)
		if (data.uom_id !== undefined) {
			const { uom_name } = await sqlUtil.lookupdb(db, 'public.uom', 'uom_id', data.uom_id)
			data.uom_name = uom_name ?? null
		}
		// lookup: sea_name dari field sea_name pada table public.sea dimana (public.sea.sea_id = public.sku.sea_id)
		if (data.sea_id !== undefined) {
			const { sea_name } = await sqlUtil.lookupdb(db, 'public.sea', 'sea_id', data.sea_id)
			data.sea_name = sea_name ?? null
		}
		 
		// lookup data createby
		if (data._createby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		if (data._modifyby !== undefined) {
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function sku_headerCreate(self, body) {
	const { source='sku', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._createby = user_id
		data._createdate = data_timestamp
		data._timestamp = data_timestamp

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

			
			// buat short sequencer	
			const sequencer = createSequencerLine(tx, {})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate short id sesuai prefix (default: ) reset pertahun
			const seqdata = await sequencer.yearlyshort(args.doc_id)
			data.sku_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}

			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			sku_log(self, body, startTime, tablename, ret.sku_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function sku_headerUpdate(self, body) {
	const { source='sku', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)

		const data_timestamp = (new Date()).toISOString()

		data._modifyby = user_id
		data._modifydate = data_timestamp
		data._timestamp = data_timestamp


		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['sku_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			sku_log(self, body, startTime, tablename, data.sku_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function sku_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {sku_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['sku_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			sku_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}


	