-- prop.sql


/* =============================================
 * CREATE TABLE public."prop"
 * ============================================*/
create table public."prop" (
	prop_id smallint generated by default as identity,
	constraint prop_pk primary key (prop_id)
);
comment on table public."prop" is '';	


-- =============================================
-- FIELD: prop_name text
-- =============================================
-- ADD prop_name
alter table public."prop" add prop_name text  ;
comment on column public."prop".prop_name is '';

-- MODIFY prop_name
alter table public."prop"
	alter column prop_name type text,
	ALTER COLUMN prop_name DROP DEFAULT,
	ALTER COLUMN prop_name DROP NOT NULL;
comment on column public."prop".prop_name is '';


-- =============================================
-- FIELD: prop_descr text
-- =============================================
-- ADD prop_descr
alter table public."prop" add prop_descr text  ;
comment on column public."prop".prop_descr is '';

-- MODIFY prop_descr
alter table public."prop"
	alter column prop_descr type text,
	ALTER COLUMN prop_descr DROP DEFAULT,
	ALTER COLUMN prop_descr DROP NOT NULL;
comment on column public."prop".prop_descr is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."prop" add _createby integer not null ;
comment on column public."prop"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."prop"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."prop"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."prop" add _createdate timestamp with time zone not null default now();
comment on column public."prop"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."prop"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."prop"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."prop" add _modifyby integer  ;
comment on column public."prop"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."prop"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."prop"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."prop" add _modifydate timestamp with time zone  ;
comment on column public."prop"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."prop"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."prop"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."prop" add _timestamp timestamp with time zone not null default now();
comment on column public."prop"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."prop"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."prop"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$prop$_timestamp;
CREATE INDEX idx$public$prop$_timestamp ON public.prop (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Add unique index 
alter table  public."prop"
	add constraint uq$public$prop$prop_name unique (prop_name); 

