-- gro.sql


/* =============================================
 * CREATE TABLE public."gro"
 * ============================================*/
create table public."gro" (
	gro_id int generated by default as identity,
	constraint gro_pk primary key (gro_id)
);
comment on table public."gro" is '';	


-- =============================================
-- FIELD: gro_isdisabled boolean
-- =============================================
-- ADD gro_isdisabled
alter table public."gro" add gro_isdisabled boolean not null default false;
comment on column public."gro".gro_isdisabled is '';

-- MODIFY gro_isdisabled
alter table public."gro"
	alter column gro_isdisabled type boolean,
	ALTER COLUMN gro_isdisabled SET DEFAULT false,
	ALTER COLUMN gro_isdisabled SET NOT NULL;
comment on column public."gro".gro_isdisabled is '';


-- =============================================
-- FIELD: gro_name text
-- =============================================
-- ADD gro_name
alter table public."gro" add gro_name text not null default '';
comment on column public."gro".gro_name is '';

-- MODIFY gro_name
alter table public."gro"
	alter column gro_name type text,
	ALTER COLUMN gro_name SET DEFAULT '',
	ALTER COLUMN gro_name SET NOT NULL;
comment on column public."gro".gro_name is '';


-- =============================================
-- FIELD: gro_descr text
-- =============================================
-- ADD gro_descr
alter table public."gro" add gro_descr text  ;
comment on column public."gro".gro_descr is '';

-- MODIFY gro_descr
alter table public."gro"
	alter column gro_descr type text,
	ALTER COLUMN gro_descr DROP DEFAULT,
	ALTER COLUMN gro_descr DROP NOT NULL;
comment on column public."gro".gro_descr is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."gro" add _createby integer not null ;
comment on column public."gro"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."gro"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."gro"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."gro" add _createdate timestamp with time zone not null default now();
comment on column public."gro"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."gro"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."gro"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."gro" add _modifyby integer  ;
comment on column public."gro"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."gro"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."gro"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."gro" add _modifydate timestamp with time zone  ;
comment on column public."gro"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."gro"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."gro"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."gro" add _timestamp timestamp with time zone not null default now();
comment on column public."gro"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."gro"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."gro"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$gro$_timestamp;
CREATE INDEX idx$public$gro$_timestamp ON public.gro (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."gro"
	drop constraint uq$public$gro$gro_name;
	

-- Add unique index 
alter table  public."gro"
	add constraint uq$public$gro$gro_name unique (gro_name); 

