-- tax.sql


/* =============================================
 * CREATE TABLE public."tax"
 * ============================================*/
create table public."tax" (
	tax_id smallint generated by default as identity,
	constraint tax_pk primary key (tax_id)
);
comment on table public."tax" is '';	


-- =============================================
-- FIELD: tax_isdisabled boolean
-- =============================================
-- ADD tax_isdisabled
alter table public."tax" add tax_isdisabled boolean not null default false;
comment on column public."tax".tax_isdisabled is '';

-- MODIFY tax_isdisabled
alter table public."tax"
	alter column tax_isdisabled type boolean,
	ALTER COLUMN tax_isdisabled SET DEFAULT false,
	ALTER COLUMN tax_isdisabled SET NOT NULL;
comment on column public."tax".tax_isdisabled is '';


-- =============================================
-- FIELD: tax_name text
-- =============================================
-- ADD tax_name
alter table public."tax" add tax_name text  ;
comment on column public."tax".tax_name is '';

-- MODIFY tax_name
alter table public."tax"
	alter column tax_name type text,
	ALTER COLUMN tax_name DROP DEFAULT,
	ALTER COLUMN tax_name DROP NOT NULL;
comment on column public."tax".tax_name is '';


-- =============================================
-- FIELD: tax_value decimal(4, 2)
-- =============================================
-- ADD tax_value
alter table public."tax" add tax_value decimal(4, 2) not null default 0;
comment on column public."tax".tax_value is '';

-- MODIFY tax_value
alter table public."tax"
	alter column tax_value type decimal(4, 2),
	ALTER COLUMN tax_value SET DEFAULT 0,
	ALTER COLUMN tax_value SET NOT NULL;
comment on column public."tax".tax_value is '';


-- =============================================
-- FIELD: tax_isinclude boolean
-- =============================================
-- ADD tax_isinclude
alter table public."tax" add tax_isinclude boolean not null default false;
comment on column public."tax".tax_isinclude is '';

-- MODIFY tax_isinclude
alter table public."tax"
	alter column tax_isinclude type boolean,
	ALTER COLUMN tax_isinclude SET DEFAULT false,
	ALTER COLUMN tax_isinclude SET NOT NULL;
comment on column public."tax".tax_isinclude is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."tax" add _createby integer not null ;
comment on column public."tax"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."tax"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."tax"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."tax" add _createdate timestamp with time zone not null default now();
comment on column public."tax"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."tax"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."tax"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."tax" add _modifyby integer  ;
comment on column public."tax"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."tax"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."tax"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."tax" add _modifydate timestamp with time zone  ;
comment on column public."tax"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."tax"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."tax"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."tax" add _timestamp timestamp with time zone not null default now();
comment on column public."tax"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."tax"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."tax"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$tax$_timestamp;
CREATE INDEX idx$public$tax$_timestamp ON public.tax (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."tax"
	drop constraint uq$public$tax$tax_name;
	

-- Add unique index 
alter table  public."tax"
	add constraint uq$public$tax$tax_name unique (tax_name); 

