-- itemclass.sql


/* =============================================
 * CREATE TABLE public."itemclass"
 * ============================================*/
create table public."itemclass" (
	itemclass_id int generated by default as identity,
	constraint itemclass_pk primary key (itemclass_id)
);
comment on table public."itemclass" is '';	


-- =============================================
-- FIELD: itemclass_isdisabled boolean
-- =============================================
-- ADD itemclass_isdisabled
alter table public."itemclass" add itemclass_isdisabled boolean not null default false;
comment on column public."itemclass".itemclass_isdisabled is '';

-- MODIFY itemclass_isdisabled
alter table public."itemclass"
	alter column itemclass_isdisabled type boolean,
	ALTER COLUMN itemclass_isdisabled SET DEFAULT false,
	ALTER COLUMN itemclass_isdisabled SET NOT NULL;
comment on column public."itemclass".itemclass_isdisabled is '';


-- =============================================
-- FIELD: itemclass_name text
-- =============================================
-- ADD itemclass_name
alter table public."itemclass" add itemclass_name text  ;
comment on column public."itemclass".itemclass_name is '';

-- MODIFY itemclass_name
alter table public."itemclass"
	alter column itemclass_name type text,
	ALTER COLUMN itemclass_name DROP DEFAULT,
	ALTER COLUMN itemclass_name DROP NOT NULL;
comment on column public."itemclass".itemclass_name is '';


-- =============================================
-- FIELD: itemclass_descr text
-- =============================================
-- ADD itemclass_descr
alter table public."itemclass" add itemclass_descr text  ;
comment on column public."itemclass".itemclass_descr is '';

-- MODIFY itemclass_descr
alter table public."itemclass"
	alter column itemclass_descr type text,
	ALTER COLUMN itemclass_descr DROP DEFAULT,
	ALTER COLUMN itemclass_descr DROP NOT NULL;
comment on column public."itemclass".itemclass_descr is '';


-- =============================================
-- FIELD: owner_struct_id int
-- =============================================
-- ADD owner_struct_id
alter table public."itemclass" add owner_struct_id int  ;
comment on column public."itemclass".owner_struct_id is '';

-- MODIFY owner_struct_id
alter table public."itemclass"
	alter column owner_struct_id type int,
	ALTER COLUMN owner_struct_id DROP DEFAULT,
	ALTER COLUMN owner_struct_id DROP NOT NULL;
comment on column public."itemclass".owner_struct_id is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."itemclass" add _createby integer not null ;
comment on column public."itemclass"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."itemclass"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."itemclass"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."itemclass" add _createdate timestamp with time zone not null default now();
comment on column public."itemclass"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."itemclass"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."itemclass"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."itemclass" add _modifyby integer  ;
comment on column public."itemclass"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."itemclass"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."itemclass"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."itemclass" add _modifydate timestamp with time zone  ;
comment on column public."itemclass"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."itemclass"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."itemclass"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE public."itemclass" DROP CONSTRAINT fk$public$itemclass$owner_struct_id;


-- Add Foreign Key Constraint  
ALTER TABLE public."itemclass"
	ADD CONSTRAINT fk$public$itemclass$owner_struct_id
	FOREIGN KEY (owner_struct_id)
	REFERENCES public."struct"(struct_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS public.idx_fk$public$itemclass$owner_struct_id;
CREATE INDEX idx_fk$public$itemclass$owner_struct_id ON public."itemclass"(owner_struct_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."itemclass"
	drop constraint uq$public$itemclass$itemclass_name;
	

-- Add unique index 
alter table  public."itemclass"
	add constraint uq$public$itemclass$itemclass_name unique (itemclass_name); 

