-- billtype.sql


/* =============================================
 * CREATE TABLE public."billtype"
 * ============================================*/
create table public."billtype" (
	billtype_id smallint generated by default as identity,
	constraint billtype_pk primary key (billtype_id)
);
comment on table public."billtype" is '';	


-- =============================================
-- FIELD: billtype_isdisabled boolean
-- =============================================
-- ADD billtype_isdisabled
alter table public."billtype" add billtype_isdisabled boolean not null default false;
comment on column public."billtype".billtype_isdisabled is '';

-- MODIFY billtype_isdisabled
alter table public."billtype"
	alter column billtype_isdisabled type boolean,
	ALTER COLUMN billtype_isdisabled SET DEFAULT false,
	ALTER COLUMN billtype_isdisabled SET NOT NULL;
comment on column public."billtype".billtype_isdisabled is '';


-- =============================================
-- FIELD: billtype_name text
-- =============================================
-- ADD billtype_name
alter table public."billtype" add billtype_name text  ;
comment on column public."billtype".billtype_name is '';

-- MODIFY billtype_name
alter table public."billtype"
	alter column billtype_name type text,
	ALTER COLUMN billtype_name DROP DEFAULT,
	ALTER COLUMN billtype_name DROP NOT NULL;
comment on column public."billtype".billtype_name is '';


-- =============================================
-- FIELD: billtype_descr text
-- =============================================
-- ADD billtype_descr
alter table public."billtype" add billtype_descr text  ;
comment on column public."billtype".billtype_descr is '';

-- MODIFY billtype_descr
alter table public."billtype"
	alter column billtype_descr type text,
	ALTER COLUMN billtype_descr DROP DEFAULT,
	ALTER COLUMN billtype_descr DROP NOT NULL;
comment on column public."billtype".billtype_descr is '';


-- =============================================
-- FIELD: isrefpo boolean
-- =============================================
-- ADD isrefpo
alter table public."billtype" add isrefpo boolean not null default false;
comment on column public."billtype".isrefpo is '';

-- MODIFY isrefpo
alter table public."billtype"
	alter column isrefpo type boolean,
	ALTER COLUMN isrefpo SET DEFAULT false,
	ALTER COLUMN isrefpo SET NOT NULL;
comment on column public."billtype".isrefpo is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."billtype" add _createby integer not null ;
comment on column public."billtype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."billtype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."billtype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."billtype" add _createdate timestamp with time zone not null default now();
comment on column public."billtype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."billtype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."billtype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."billtype" add _modifyby integer  ;
comment on column public."billtype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."billtype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."billtype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."billtype" add _modifydate timestamp with time zone  ;
comment on column public."billtype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."billtype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."billtype"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."billtype" add _timestamp timestamp with time zone not null default now();
comment on column public."billtype"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."billtype"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."billtype"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$billtype$_timestamp;
CREATE INDEX idx$public$billtype$_timestamp ON public.billtype (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."billtype"
	drop constraint uq$public$billtype$billtype_name;
	

-- Add unique index 
alter table  public."billtype"
	add constraint uq$public$billtype$billtype_name unique (billtype_name); 

