-- curr.sql


/* =============================================
 * CREATE TABLE public."curr"
 * ============================================*/
create table public."curr" (
	curr_id smallint generated by default as identity,
	constraint curr_pk primary key (curr_id)
);
comment on table public."curr" is '';	


-- =============================================
-- FIELD: curr_name text
-- =============================================
-- ADD curr_name
alter table public."curr" add curr_name text  ;
comment on column public."curr".curr_name is '';

-- MODIFY curr_name
alter table public."curr"
	alter column curr_name type text,
	ALTER COLUMN curr_name DROP DEFAULT,
	ALTER COLUMN curr_name DROP NOT NULL;
comment on column public."curr".curr_name is '';


-- =============================================
-- FIELD: curr_descr text
-- =============================================
-- ADD curr_descr
alter table public."curr" add curr_descr text  ;
comment on column public."curr".curr_descr is '';

-- MODIFY curr_descr
alter table public."curr"
	alter column curr_descr type text,
	ALTER COLUMN curr_descr DROP DEFAULT,
	ALTER COLUMN curr_descr DROP NOT NULL;
comment on column public."curr".curr_descr is '';


-- =============================================
-- FIELD: curr_code text
-- =============================================
-- ADD curr_code
alter table public."curr" add curr_code text  ;
comment on column public."curr".curr_code is '';

-- MODIFY curr_code
alter table public."curr"
	alter column curr_code type text,
	ALTER COLUMN curr_code DROP DEFAULT,
	ALTER COLUMN curr_code DROP NOT NULL;
comment on column public."curr".curr_code is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."curr" add _createby integer not null ;
comment on column public."curr"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."curr"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."curr"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."curr" add _createdate timestamp with time zone not null default now();
comment on column public."curr"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."curr"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."curr"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."curr" add _modifyby integer  ;
comment on column public."curr"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."curr"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."curr"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."curr" add _modifydate timestamp with time zone  ;
comment on column public."curr"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."curr"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."curr"._modifydate is 'waktu terakhir record dimodifikasi';






-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table public."curr"
	drop constraint uq$public$curr$curr_name;
	

-- Add unique index 
alter table  public."curr"
	add constraint uq$public$curr$curr_name unique (curr_name); 

