-- variancetype.sql


/* =============================================
 * CREATE TABLE public."variancetype"
 * ============================================*/
create table public."variancetype" (
	variancetype_id smallint generated by default as identity,
	constraint variancetype_pk primary key (variancetype_id)
);
comment on table public."variancetype" is '';	


-- =============================================
-- FIELD: variancetype_name text
-- =============================================
-- ADD variancetype_name
alter table public."variancetype" add variancetype_name text  ;
comment on column public."variancetype".variancetype_name is '';

-- MODIFY variancetype_name
alter table public."variancetype"
	alter column variancetype_name type text,
	ALTER COLUMN variancetype_name DROP DEFAULT,
	ALTER COLUMN variancetype_name DROP NOT NULL;
comment on column public."variancetype".variancetype_name is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table public."variancetype" add _createby integer not null ;
comment on column public."variancetype"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table public."variancetype"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column public."variancetype"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table public."variancetype" add _createdate timestamp with time zone not null default now();
comment on column public."variancetype"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table public."variancetype"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column public."variancetype"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table public."variancetype" add _modifyby integer  ;
comment on column public."variancetype"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table public."variancetype"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column public."variancetype"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table public."variancetype" add _modifydate timestamp with time zone  ;
comment on column public."variancetype"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table public."variancetype"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column public."variancetype"._modifydate is 'waktu terakhir record dimodifikasi';


-- =============================================
-- FIELD: _timestamp timestamp with time zone
-- =============================================
-- ADD _timestamp
alter table public."variancetype" add _timestamp timestamp with time zone not null default now();
comment on column public."variancetype"._timestamp is 'data timestamp';

-- MODIFY _timestamp
alter table public."variancetype"
	alter column _timestamp type timestamp with time zone,
	ALTER COLUMN _timestamp SET DEFAULT now(),
	ALTER COLUMN _timestamp SET NOT NULL;
comment on column public."variancetype"._timestamp is 'data timestamp';


-- =============================================
-- INDEX
-- =============================================
DROP INDEX IF EXISTS public.idx$public$variancetype$_timestamp;
CREATE INDEX idx$public$variancetype$_timestamp ON public.variancetype (_timestamp);




-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Add unique index 
alter table  public."variancetype"
	add constraint uq$public$variancetype$variancetype_name unique (variancetype_name); 

